// ---- Brilliance 2025 ----

registerSet("brilliance-2025", {
  label:   "Brilliance 2025",
  year:    "2025",
  series:  "Brilliance",
  subsets: [
    "Brilliance Signature",
    "Silver Brilliance",
    "Premiership Captain & Coach Signature"
  ],
  badge: {
    "Brilliance Signature":                   "b-br25-sig",
    "Silver Brilliance":                      "b-br25-sil",
    "Premiership Captain & Coach Signature":  "b-br25-cc"
  },
  label_short: {
    "Brilliance Signature":                   "Signature",
    "Silver Brilliance":                      "Silver",
    "Premiership Captain & Coach Signature":  "Prem. Cptn & Coach"
  }
});

var CARDS_BRILLIANCE_2025 = [
  ['BS-JD','Jordan Dawson','Brilliance Signature','Adelaide Crows'],
  ['BS-SD','Sid Draper','Brilliance Signature','Adelaide Crows'],
  ['BS-MR','Mark Ricciuto','Brilliance Signature','Adelaide Crows'],
  ['BS-CR','Cam Rayner','Brilliance Signature','Brisbane Lions'],
  ['BS-LA','Levi Ashcroft','Brilliance Signature','Brisbane Lions'],
  ['BS-JDr','Joe Daniher','Brilliance Signature','Brisbane Lions'],
  ['BS-CC','Charlie Curnow','Brilliance Signature','Carlton'],
  ['BS-OH','Ollie Hollands','Brilliance Signature','Carlton'],
  ['BS-AW','Andrew Walker','Brilliance Signature','Carlton'],
  ['BS-DH','Dan Houston','Brilliance Signature','Collingwood'],
  ['BS-ND','Nick Daicos','Brilliance Signature','Collingwood'],
  ['BS-NM','Nick Maxwell','Brilliance Signature','Collingwood'],
  ['BS-KL','Kyle Langford','Brilliance Signature','Essendon'],
  ['BS-IK','Isaac Kako','Brilliance Signature','Essendon'],
  ['BS-DF','Dustin Fletcher','Brilliance Signature','Essendon'],
  ['BS-SB','Shai Bolton','Brilliance Signature','Fremantle'],
  ['BS-MRd','Murphy Reid','Brilliance Signature','Fremantle'],
  ['BS-HB','Hayden Ballantyne','Brilliance Signature','Fremantle'],
  ['BS-BS','Bailey Smith','Brilliance Signature','Geelong Cats'],
  ['BS-LH','Lawson Humphries','Brilliance Signature','Geelong Cats'],
  ['BS-ZT','Zach Tuohy','Brilliance Signature','Geelong Cats'],
  ['BS-ST','Sam Taylor','Brilliance Signature','GWS GIANTS'],
  ['BS-AC','Aaron Cadman','Brilliance Signature','GWS GIANTS'],
  ['BS-SM','Shane Mumford','Brilliance Signature','GWS GIANTS'],
  ['BS-NA','Noah Anderson','Brilliance Signature','Gold Coast SUNS'],
  ['BS-JW','Jed Walter','Brilliance Signature','Gold Coast SUNS'],
  ['BS-GA','Gary Ablett Jnr','Brilliance Signature','Gold Coast SUNS'],
  ['BS-JB','Josh Battle','Brilliance Signature','Hawthorn'],
  ['BS-CM','Cam Mackenzie','Brilliance Signature','Hawthorn'],
  ['BS-BSl','Jordan Lewis','Brilliance Signature','Hawthorn'],
  ['BS-KP','Kysaiah Pickett','Brilliance Signature','Melbourne'],
  ['BS-HL','Harvey Langford','Brilliance Signature','Melbourne'],
  ['BS-GL','Garry Lyon','Brilliance Signature','Melbourne'],
  ['BS-GW','George Wardlaw','Brilliance Signature','North Melbourne'],
  ['BS-FO','Finn O\'Sullivan','Brilliance Signature','North Melbourne'],
  ['BS-AS','Anthony Stevens','Brilliance Signature','North Melbourne'],
  ['BS-CRe','Connor Rozee','Brilliance Signature','Port Adelaide'],
  ['BS-MB','Miles Bergman','Brilliance Signature','Port Adelaide'],
  ['BS-BL','Brendon Lade','Brilliance Signature','Port Adelaide'],
  ['BS-NB','Nathan Broad','Brilliance Signature','Richmond'],
  ['BS-SL','Sam Lalor','Brilliance Signature','Richmond'],
  ['BS-RH','Royce Hart','Brilliance Signature','Richmond'],
  ['BS-JM','Jack Macrae','Brilliance Signature','St Kilda'],
  ['BS-DW','Darcy Wilson','Brilliance Signature','St Kilda'],
  ['BS-NW','Nicky Winmar','Brilliance Signature','St Kilda'],
  ['BS-CW','Chad Warner','Brilliance Signature','Sydney Swans'],
  ['BS-EG','Errol Gulden','Brilliance Signature','Sydney Swans'],
  ['BS-BK','Brett Kirk','Brilliance Signature','Sydney Swans'],
  ['BS-LB','Liam Baker','Brilliance Signature','West Coast Eagles'],
  ['BS-HR','Harley Reid','Brilliance Signature','West Coast Eagles'],
  ['BS-GM','Guy McKenna','Brilliance Signature','West Coast Eagles'],
  ['BS-TL','Tom Liberatore','Brilliance Signature','Western Bulldogs'],
  ['BS-SDy','Sam Darcy','Brilliance Signature','Western Bulldogs'],
  ['BS-DM','Dale Morris','Brilliance Signature','Western Bulldogs'],
  ['B-JD','Jordan Dawson','Silver Brilliance','Adelaide Crows'],
  ['B-SD','Sid Draper','Silver Brilliance','Adelaide Crows'],
  ['B-MR','Mark Ricciuto','Silver Brilliance','Adelaide Crows'],
  ['B-CR','Cam Rayner','Silver Brilliance','Brisbane Lions'],
  ['B-LA','Levi Ashcroft','Silver Brilliance','Brisbane Lions'],
  ['B-JDr','Joe Daniher','Silver Brilliance','Brisbane Lions'],
  ['B-CC','Charlie Curnow','Silver Brilliance','Carlton'],
  ['B-OH','Ollie Hollands','Silver Brilliance','Carlton'],
  ['B-AW','Andrew Walker','Silver Brilliance','Carlton'],
  ['B-DH','Dan Houston','Silver Brilliance','Collingwood'],
  ['B-ND','Nick Daicos','Silver Brilliance','Collingwood'],
  ['B-NM','Nick Maxwell','Silver Brilliance','Collingwood'],
  ['B-KL','Kyle Langford','Silver Brilliance','Essendon'],
  ['B-IK','Isaac Kako','Silver Brilliance','Essendon'],
  ['B-DF','Dustin Fletcher','Silver Brilliance','Essendon'],
  ['B-SB','Shai Bolton','Silver Brilliance','Fremantle'],
  ['B-MRd','Murphy Reid','Silver Brilliance','Fremantle'],
  ['B-HB','Hayden Ballantyne','Silver Brilliance','Fremantle'],
  ['B-BS','Bailey Smith','Silver Brilliance','Geelong Cats'],
  ['B-LH','Lawson Humphries','Silver Brilliance','Geelong Cats'],
  ['B-ZT','Zach Tuohy','Silver Brilliance','Geelong Cats'],
  ['B-ST','Sam Taylor','Silver Brilliance','GWS GIANTS'],
  ['B-AC','Aaron Cadman','Silver Brilliance','GWS GIANTS'],
  ['B-SM','Shane Mumford','Silver Brilliance','GWS GIANTS'],
  ['B-NA','Noah Anderson','Silver Brilliance','Gold Coast SUNS'],
  ['B-JW','Jed Walter','Silver Brilliance','Gold Coast SUNS'],
  ['B-GA','Gary Ablett Jnr','Silver Brilliance','Gold Coast SUNS'],
  ['B-JB','Josh Battle','Silver Brilliance','Hawthorn'],
  ['B-CM','Cam Mackenzie','Silver Brilliance','Hawthorn'],
  ['B-BSl','Jordan Lewis','Silver Brilliance','Hawthorn'],
  ['B-KP','Kysaiah Pickett','Silver Brilliance','Melbourne'],
  ['B-HL','Harvey Langford','Silver Brilliance','Melbourne'],
  ['B-GL','Garry Lyon','Silver Brilliance','Melbourne'],
  ['B-GW','George Wardlaw','Silver Brilliance','North Melbourne'],
  ['B-FO','Finn O\'Sullivan','Silver Brilliance','North Melbourne'],
  ['B-AS','Anthony Stevens','Silver Brilliance','North Melbourne'],
  ['B-CRe','Connor Rozee','Silver Brilliance','Port Adelaide'],
  ['B-MB','Miles Bergman','Silver Brilliance','Port Adelaide'],
  ['B-BL','Brendon Lade','Silver Brilliance','Port Adelaide'],
  ['B-NB','Nathan Broad','Silver Brilliance','Richmond'],
  ['B-SL','Sam Lalor','Silver Brilliance','Richmond'],
  ['B-RH','Royce Hart','Silver Brilliance','Richmond'],
  ['B-JM','Jack Macrae','Silver Brilliance','St Kilda'],
  ['B-DW','Darcy Wilson','Silver Brilliance','St Kilda'],
  ['B-NW','Nicky Winmar','Silver Brilliance','St Kilda'],
  ['B-CW','Chad Warner','Silver Brilliance','Sydney Swans'],
  ['B-EG','Errol Gulden','Silver Brilliance','Sydney Swans'],
  ['B-BK','Brett Kirk','Silver Brilliance','Sydney Swans'],
  ['B-LB','Liam Baker','Silver Brilliance','West Coast Eagles'],
  ['B-HR','Harley Reid','Silver Brilliance','West Coast Eagles'],
  ['B-GM','Guy McKenna','Silver Brilliance','West Coast Eagles'],
  ['B-TL','Tom Liberatore','Silver Brilliance','Western Bulldogs'],
  ['B-SDy','Sam Darcy','Silver Brilliance','Western Bulldogs'],
  ['B-DM','Dale Morris','Silver Brilliance','Western Bulldogs'],
  ['CCS11','Harris Andrews / Lachie Neale / Chris Fagan','Premiership Captain & Coach Signature','Brisbane Lions'],
  ['CCS12','Darcy Moore / Craig McRae','Premiership Captain & Coach Signature','Collingwood'],
  ['CCS13','Joel Selwood / Chris Scott','Premiership Captain & Coach Signature','Geelong Cats'],
  ['CCS14','Easton Wood / Robert Murphy / Luke Beveridge','Premiership Captain & Coach Signature','Western Bulldogs']
];
