// ---- Debutants 2025 ----
(function() {
  const s = document.createElement('style');
  s.textContent = `
  .b-d25-dp { background: #9333ea; }
  .b-d25-d { background: #d97706; }
  `;
  document.head.appendChild(s);
})();

registerSet("debutants-2025", {
  label:   "Debutants 2025",
  year:    "2025",
  series:  "Debutants",
  subsets: [
    "Debutant",
    "Debutant Platinum",
  ],
  badge: {
    "Debutant": "b-d25-d",
    "Debutant Platinum": "b-d25-dp",
  },
  label_short: {
    "Debutant": "Debutant",
    "Debutant Platinum": "Platinum",
  }
});

var CARDS_DEBUTANTS_2025 = [
  ['DG1','Tom Hanily','Debutant','Sydney Swans'],
  ['DG2','James Leake','Debutant','GWS GIANTS'],
  ['DG3','Harry Armstrong','Debutant','Richmond'],
  ['DG4','Sam Lalor','Debutant','Richmond'],
  ['DG5','Luke Trainor','Debutant','Richmond'],
  ['DG6','Lucas Camporeale','Debutant','Carlton'],
  ['DG7','Isaac Kako','Debutant','Essendon'],
  ['DG8','Murphy Reid','Debutant','Fremantle'],
  ['DG9','Riley Bice','Debutant','Sydney Swans'],
  ['DG10','Levi Ashcroft','Debutant','Brisbane Lions'],
  ['DG11','Sam Davidson','Debutant','Western Bulldogs'],
  ['DG12','Josh Dolan','Debutant','Western Bulldogs'],
  ['DG13','Jacob Konstanty','Debutant','North Melbourne'],
  ['DG14','Finn O\'Sullivan','Debutant','North Melbourne'],
  ['DG15','Joe Berry','Debutant','Port Adelaide'],
  ['DG16','Harry Boyd','Debutant','St Kilda'],
  ['DG17','Max Hall','Debutant','St Kilda'],
  ['DG18','Liam O\'Connell','Debutant','St Kilda'],
  ['DG19','Sid Draper','Debutant','Adelaide Crows'],
  ['DG20','Jack Henderson','Debutant','Melbourne'],
  ['DG21','Matthew Jefferson','Debutant','Melbourne'],
  ['DG22','Aidan Johnson','Debutant','Melbourne'],
  ['DG23','Harvey Langford','Debutant','Melbourne'],
  ['DG24','Xavier Lindsay','Debutant','Melbourne'],
  ['DG25','Archer Reid','Debutant','West Coast Eagles'],
  ['DG26','Thomas Edwards','Debutant','Essendon'],
  ['DG27','Christian Moraes','Debutant','Port Adelaide'],
  ['DG28','Liam Fawcett','Debutant','Richmond'],
  ['DG29','Isaac Keeler','Debutant','St Kilda'],
  ['DG30','Will McLachlan','Debutant','Brisbane Lions'],
  ['DG31','Saad El-Hawli','Debutant','Essendon'],
  ['DG32','Tom Cochrane','Debutant','Port Adelaide'],
  ['DG33','Tobie Travaglia','Debutant','St Kilda'],
  ['DG34','Isaiah Dudley','Debutant','Fremantle'],
  ['DG35','Will White','Debutant','Carlton'],
  ['DG36','Matt Whitlock','Debutant','North Melbourne'],
  ['DG37','Sandy Brock','Debutant','West Coast Eagles'],
  ['DG38','Hamish Davis','Debutant','West Coast Eagles'],
  ['DG39','Tom Gross','Debutant','West Coast Eagles'],
  ['DG40','Matthew Carroll','Debutant','Carlton'],
  ['DG41','Cooper Hynes','Debutant','Western Bulldogs'],
  ['DG42','Jonty Faull','Debutant','Richmond'],
  ['DG43','Sam Marshall','Debutant','Brisbane Lions'],
  ['DG44','Campbell Gray','Debutant','Richmond'],
  ['DG45','Jedd Busslinger','Debutant','Western Bulldogs'],
  ['DG46','Oliver Wiltshire','Debutant','Geelong Cats'],
  ['DG47','Finnbar Maley','Debutant','North Melbourne'],
  ['DG48','Hugh Boxshall','Debutant','St Kilda'],
  ['DG49','Bo Allan','Debutant','West Coast Eagles'],
  ['DG50','Josaia Delana','Debutant','GWS GIANTS'],
  ['DG51','Lewis Hayes','Debutant','Essendon'],
  ['DG52','Archer Day-Wicks','Debutant','Essendon'],
  ['DG53','Thomas Sims','Debutant','Richmond'],
  ['DG54','Cody Angove','Debutant','GWS GIANTS'],
  ['DG55','Angus Clarke','Debutant','Essendon'],
  ['DG56','Harry O\'Farrell','Debutant','Carlton'],
  ['DG57','Will Hayes','Debutant','Collingwood'],
  ['DG58','Hugh Jackson','Debutant','Port Adelaide'],
  ['DG59','Zak Johnson','Debutant','Essendon'],
  ['DG60','Leo Lombard','Debutant','Gold Coast SUNS'],
  ['DG61','Ty Gallop','Debutant','Brisbane Lions'],
  ['DG62','Nick Madden','Debutant','GWS GIANTS'],
  ['DG63','Hudson O\'Keeffe','Debutant','Carlton'],
  ['DG64','Luamon Lual','Debutant','Essendon'],
  ['DG65','Lachlan Blakiston','Debutant','Essendon'],
  ['DG66','Archer May','Debutant','Essendon'],
  ['DG67','Mani Liddy','Debutant','Port Adelaide'],
  ['DG68','Tom McCarthy','Debutant','West Coast Eagles'],
  ['DG69','Vigo Visentini','Debutant','Essendon'],
  ['DG70','Alix Tauru','Debutant','St Kilda'],
  ['DG71','Jasper Alger','Debutant','Richmond'],
  ['DG72','Billy Wilson','Debutant','Carlton'],
  ['DG73','Flynn Young','Debutant','Carlton'],
  ['DG74','Charlie West','Debutant','Collingwood'],
  ['DG75','Jobe Shanahan','Debutant','West Coast Eagles'],
  ['DG76','Roan Steele','Debutant','Collingwood'],
  ['DG77','Malakai Champion','Debutant','West Coast Eagles'],
  ['DG78','Oscar Adams','Debutant','Gold Coast SUNS'],
  ['DG79','George Stevens','Debutant','Geelong Cats'],
  ['DG80','Taj Hotton','Debutant','Richmond'],
  ['DG81','Oskar Smartt','Debutant','Essendon'],
  ['DG82','Max Heath','Debutant','St Kilda'],
  ['DG83','Liam McMahon','Debutant','Essendon'],
  ['DG84','Zac Banch','Debutant','North Melbourne'],
  ['DG85','Ben Jepson','Debutant','Gold Coast SUNS'],
  ['DG86','Jack Whitlock','Debutant','Port Adelaide'],
  ['DG87','Jayden Nguyen','Debutant','Essendon'],
  ['DG88','Jesse Dattoli','Debutant','Sydney Swans'],
  ['DG89','Cooper Trembath','Debutant','North Melbourne'],
  ['DG90','Geordie Payne','Debutant','North Melbourne'],
  ['DG91','Jed Adams','Debutant','Melbourne'],
  ['DG92','Rhys Unwin','Debutant','Essendon'],
  ['DG93','Alex Dodson','Debutant','St Kilda'],
  ['DG94','Luke Beecken','Debutant','Brisbane Lions'],
  ['DG95','Jordan Croft','Debutant','Western Bulldogs'],
  ['DG96','Jacob Newton','Debutant','West Coast Eagles'],
  ['DG97','Harrison Ramm','Debutant','Port Adelaide'],
  ['DG98','Ewan Mackinlay','Debutant','Port Adelaide'],
  ['DG99','Lachlan Gulbin','Debutant','Gold Coast SUNS'],
  ['DG100','Lucca Grego','Debutant','West Coast Eagles'],
  ['DP1','Tom Hanily','Debutant Platinum','Sydney Swans'],
  ['DP2','James Leake','Debutant Platinum','GWS GIANTS'],
  ['DP3','Harry Armstrong','Debutant Platinum','Richmond'],
  ['DP4','Sam Lalor','Debutant Platinum','Richmond'],
  ['DP5','Luke Trainor','Debutant Platinum','Richmond'],
  ['DP6','Lucas Camporeale','Debutant Platinum','Carlton'],
  ['DP7','Isaac Kako','Debutant Platinum','Essendon'],
  ['DP8','Murphy Reid','Debutant Platinum','Fremantle'],
  ['DP9','Riley Bice','Debutant Platinum','Sydney Swans'],
  ['DP10','Levi Ashcroft','Debutant Platinum','Brisbane Lions'],
  ['DP11','Sam Davidson','Debutant Platinum','Western Bulldogs'],
  ['DP12','Josh Dolan','Debutant Platinum','Western Bulldogs'],
  ['DP13','Jacob Konstanty','Debutant Platinum','North Melbourne'],
  ['DP14','Finn O\'Sullivan','Debutant Platinum','North Melbourne'],
  ['DP15','Joe Berry','Debutant Platinum','Port Adelaide'],
  ['DP16','Harry Boyd','Debutant Platinum','St Kilda'],
  ['DP17','Max Hall','Debutant Platinum','St Kilda'],
  ['DP18','Liam O\'Connell','Debutant Platinum','St Kilda'],
  ['DP19','Sid Draper','Debutant Platinum','Adelaide Crows'],
  ['DP20','Jack Henderson','Debutant Platinum','Melbourne'],
  ['DP21','Matthew Jefferson','Debutant Platinum','Melbourne'],
  ['DP22','Aidan Johnson','Debutant Platinum','Melbourne'],
  ['DP23','Harvey Langford','Debutant Platinum','Melbourne'],
  ['DP24','Xavier Lindsay','Debutant Platinum','Melbourne'],
  ['DP25','Archer Reid','Debutant Platinum','West Coast Eagles'],
  ['DP26','Thomas Edwards','Debutant Platinum','Essendon'],
  ['DP27','Christian Moraes','Debutant Platinum','Port Adelaide'],
  ['DP28','Liam Fawcett','Debutant Platinum','Richmond'],
  ['DP29','Isaac Keeler','Debutant Platinum','St Kilda'],
  ['DP30','Will McLachlan','Debutant Platinum','Brisbane Lions'],
  ['DP31','Saad El-Hawli','Debutant Platinum','Essendon'],
  ['DP32','Tom Cochrane','Debutant Platinum','Port Adelaide'],
  ['DP33','Tobie Travaglia','Debutant Platinum','St Kilda'],
  ['DP34','Isaiah Dudley','Debutant Platinum','Fremantle'],
  ['DP35','Will White','Debutant Platinum','Carlton'],
  ['DP36','Matt Whitlock','Debutant Platinum','North Melbourne'],
  ['DP37','Sandy Brock','Debutant Platinum','West Coast Eagles'],
  ['DP38','Hamish Davis','Debutant Platinum','West Coast Eagles'],
  ['DP39','Tom Gross','Debutant Platinum','West Coast Eagles'],
  ['DP40','Matthew Carroll','Debutant Platinum','Carlton'],
  ['DP41','Cooper Hynes','Debutant Platinum','Western Bulldogs'],
  ['DP42','Jonty Faull','Debutant Platinum','Richmond'],
  ['DP43','Sam Marshall','Debutant Platinum','Brisbane Lions'],
  ['DP44','Campbell Gray','Debutant Platinum','Richmond'],
  ['DP45','Jedd Busslinger','Debutant Platinum','Western Bulldogs'],
  ['DP46','Oliver Wiltshire','Debutant Platinum','Geelong Cats'],
  ['DP47','Finnbar Maley','Debutant Platinum','North Melbourne'],
  ['DP48','Hugh Boxshall','Debutant Platinum','St Kilda'],
  ['DP49','Bo Allan','Debutant Platinum','West Coast Eagles'],
  ['DP50','Josaia Delana','Debutant Platinum','GWS GIANTS'],
  ['DP51','Lewis Hayes','Debutant Platinum','Essendon'],
  ['DP52','Archer Day-Wicks','Debutant Platinum','Essendon'],
  ['DP53','Thomas Sims','Debutant Platinum','Richmond'],
  ['DP54','Cody Angove','Debutant Platinum','GWS GIANTS'],
  ['DP55','Angus Clarke','Debutant Platinum','Essendon'],
  ['DP56','Harry O\'Farrell','Debutant Platinum','Carlton'],
  ['DP57','Will Hayes','Debutant Platinum','Collingwood'],
  ['DP58','Hugh Jackson','Debutant Platinum','Port Adelaide'],
  ['DP59','Zak Johnson','Debutant Platinum','Essendon'],
  ['DP60','Leo Lombard','Debutant Platinum','Gold Coast SUNS'],
  ['DP61','Ty Gallop','Debutant Platinum','Brisbane Lions'],
  ['DP62','Nick Madden','Debutant Platinum','GWS GIANTS'],
  ['DP63','Hudson O\'Keeffe','Debutant Platinum','Carlton'],
  ['DP64','Luamon Lual','Debutant Platinum','Essendon'],
  ['DP65','Lachlan Blakiston','Debutant Platinum','Essendon'],
  ['DP66','Archer May','Debutant Platinum','Essendon'],
  ['DP67','Mani Liddy','Debutant Platinum','Port Adelaide'],
  ['DP68','Tom McCarthy','Debutant Platinum','West Coast Eagles'],
  ['DP69','Vigo Visentini','Debutant Platinum','Essendon'],
  ['DP70','Alix Tauru','Debutant Platinum','St Kilda'],
  ['DP71','Jasper Alger','Debutant Platinum','Richmond'],
  ['DP72','Billy Wilson','Debutant Platinum','Carlton'],
  ['DP73','Flynn Young','Debutant Platinum','Carlton'],
  ['DP74','Charlie West','Debutant Platinum','Collingwood'],
  ['DP75','Jobe Shanahan','Debutant Platinum','West Coast Eagles'],
  ['DP76','Roan Steele','Debutant Platinum','Collingwood'],
  ['DP77','Malakai Champion','Debutant Platinum','West Coast Eagles'],
  ['DP78','Oscar Adams','Debutant Platinum','Gold Coast SUNS'],
  ['DP79','George Stevens','Debutant Platinum','Geelong Cats'],
  ['DP80','Taj Hotton','Debutant Platinum','Richmond'],
  ['DP81','Oskar Smartt','Debutant Platinum','Essendon'],
  ['DP82','Max Heath','Debutant Platinum','St Kilda'],
  ['DP83','Liam McMahon','Debutant Platinum','Essendon'],
  ['DP84','Zac Banch','Debutant Platinum','North Melbourne'],
  ['DP85','Ben Jepson','Debutant Platinum','Gold Coast SUNS'],
  ['DP86','Jack Whitlock','Debutant Platinum','Port Adelaide'],
  ['DP87','Jayden Nguyen','Debutant Platinum','Essendon'],
  ['DP88','Jesse Dattoli','Debutant Platinum','Sydney Swans'],
  ['DP89','Cooper Trembath','Debutant Platinum','North Melbourne'],
  ['DP90','Geordie Payne','Debutant Platinum','North Melbourne'],
  ['DP91','Jed Adams','Debutant Platinum','Melbourne'],
  ['DP92','Rhys Unwin','Debutant Platinum','Essendon'],
  ['DP93','Alex Dodson','Debutant Platinum','St Kilda'],
  ['DP94','Luke Beecken','Debutant Platinum','Brisbane Lions'],
  ['DP95','Jordan Croft','Debutant Platinum','Western Bulldogs'],
  ['DP96','Jacob Newton','Debutant Platinum','West Coast Eagles'],
  ['DP97','Harrison Ramm','Debutant Platinum','Port Adelaide'],
  ['DP98','Ewan Mackinlay','Debutant Platinum','Port Adelaide'],
  ['DP99','Lachlan Gulbin','Debutant Platinum','Gold Coast SUNS'],
  ['DP100','Lucca Grego','Debutant Platinum','West Coast Eagles'],
];

