// ---- Seamless 2025 ----

registerSet("seamless-2025", {
  label:   "Seamless 2025",
  year:    "2025",
  series:  "Seamless",
  subsets: [
    "Base", "Black", "Solo Double Patch", "Dual Patch", "Team Multi-Patch",
    "Jumbo Patch", "Rookie Badge Signature", "Rookie Badge Signature Gold",
    "AFL Badge Signature", "Patch Signature", "Dual Patch Signature Booklet", "Mega Patch"
  ],
  badge: {
    "Base":                          "b-base",
    "Black":                         "b-black",
    "Solo Double Patch":             "b-sdp",
    "Dual Patch":                    "b-dp",
    "Team Multi-Patch":              "b-tmp",
    "Jumbo Patch":                   "b-jp",
    "Rookie Badge Signature":        "b-rs",
    "Rookie Badge Signature Gold":   "b-rsg",
    "AFL Badge Signature":           "b-as",
    "Patch Signature":               "b-ps",
    "Dual Patch Signature Booklet":  "b-psb",
    "Mega Patch":                    "b-mp"
  },
  label_short: {
    "Base":                          "Base",
    "Black":                         "Black",
    "Solo Double Patch":             "Solo DP",
    "Dual Patch":                    "Dual Patch",
    "Team Multi-Patch":              "Team MP",
    "Jumbo Patch":                   "Jumbo",
    "Rookie Badge Signature":        "Rookie Sig",
    "Rookie Badge Signature Gold":   "Rookie Sig G",
    "AFL Badge Signature":           "AFL Badge Sig",
    "Patch Signature":               "Patch Sig",
    "Dual Patch Signature Booklet":  "DP Sig Book",
    "Mega Patch":                    "Mega Patch"
  }
});

var CARDS_SEAMLESS_2025 = [
  ['1','Matt Crouch','Base','Adelaide Crows'],
  ['2','Sid Draper','Base','Adelaide Crows'],
  ['3','Darcy Fogarty','Base','Adelaide Crows'],
  ['4','Mitchell Hinge','Base','Adelaide Crows'],
  ['5','Ben Keays','Base','Adelaide Crows'],
  ['6','Rory Laird','Base','Adelaide Crows'],
  ['7','Alex Neal-Bullen','Base','Adelaide Crows'],
  ['8','Reilly O\'Brien','Base','Adelaide Crows'],
  ['9','James Peatling','Base','Adelaide Crows'],
  ['10','Josh Rachele','Base','Adelaide Crows'],
  ['11','Izak Rankine','Base','Adelaide Crows'],
  ['12','Jake Soligo','Base','Adelaide Crows'],
  ['13','Harris Andrews','Base','Brisbane Lions'],
  ['14','Zac Bailey','Base','Brisbane Lions'],
  ['15','Jarrod Berry','Base','Brisbane Lions'],
  ['16','Josh Dunkley','Base','Brisbane Lions'],
  ['17','Jaspa Fletcher','Base','Brisbane Lions'],
  ['18','Eric Hipwood','Base','Brisbane Lions'],
  ['19','Kai Lohmann','Base','Brisbane Lions'],
  ['20','Hugh McCluggage','Base','Brisbane Lions'],
  ['21','Oscar McInerney','Base','Brisbane Lions'],
  ['22','Cam Rayner','Base','Brisbane Lions'],
  ['23','Darcy Wilmot','Base','Brisbane Lions'],
  ['24','Dayne Zorko','Base','Brisbane Lions'],
  ['25','Blake Acres','Base','Carlton'],
  ['26','Adam Cerra','Base','Carlton'],
  ['27','Cooper Lord','Base','Carlton'],
  ['28','Brodie Kemp','Base','Carlton'],
  ['29','Nick Haynes','Base','Carlton'],
  ['30','George Hewett','Base','Carlton'],
  ['31','Zac Williams','Base','Carlton'],
  ['32','Harry McKay','Base','Carlton'],
  ['33','Marc Pittonet','Base','Carlton'],
  ['34','Adam Saad','Base','Carlton'],
  ['35','Harry O\'Farrell','Base','Carlton'],
  ['36','Jacob Weitering','Base','Carlton'],
  ['37','Darcy Cameron','Base','Collingwood'],
  ['38','Jack Crisp','Base','Collingwood'],
  ['39','Josh Daicos','Base','Collingwood'],
  ['40','Bobby Hill','Base','Collingwood'],
  ['41','Dan Houston','Base','Collingwood'],
  ['42','Jeremy Howe','Base','Collingwood'],
  ['43','Patrick Lipinski','Base','Collingwood'],
  ['44','Brayden Maynard','Base','Collingwood'],
  ['45','Isaac Quaynor','Base','Collingwood'],
  ['46','Harry Perryman','Base','Collingwood'],
  ['47','Lachie Schultz','Base','Collingwood'],
  ['48','Steele Sidebottom','Base','Collingwood'],
  ['49','Sam Durham','Base','Essendon'],
  ['50','Xavier Duursma','Base','Essendon'],
  ['51','Ben Hobbs','Base','Essendon'],
  ['52','Kyle Langford','Base','Essendon'],
  ['53','Nic Martin','Base','Essendon'],
  ['54','Ben McKay','Base','Essendon'],
  ['55','Andrew McGrath','Base','Essendon'],
  ['56','Archie Perkins','Base','Essendon'],
  ['57','Mason Redman','Base','Essendon'],
  ['58','Zach Reid','Base','Essendon'],
  ['59','Archie Roberts','Base','Essendon'],
  ['60','Dylan Shiel','Base','Essendon'],
  ['61','Shai Bolton','Base','Fremantle'],
  ['62','Heath Chapman','Base','Fremantle'],
  ['63','Jordan Clark','Base','Fremantle'],
  ['64','Michael Frederick','Base','Fremantle'],
  ['65','Luke Jackson','Base','Fremantle'],
  ['66','Matthew Johnson','Base','Fremantle'],
  ['67','Jaeger O\'Meara','Base','Fremantle'],
  ['68','Alex Pearce','Base','Fremantle'],
  ['69','Luke Ryan','Base','Fremantle'],
  ['70','Jeremy Sharp','Base','Fremantle'],
  ['71','Josh Treacy','Base','Fremantle'],
  ['72','Hayden Young','Base','Fremantle'],
  ['73','Tom Atkins','Base','Geelong Cats'],
  ['74','Mark Blicavs','Base','Geelong Cats'],
  ['75','Jack Bowes','Base','Geelong Cats'],
  ['76','Brad Close','Base','Geelong Cats'],
  ['77','Sam De Koning','Base','Geelong Cats'],
  ['78','Zach Guthrie','Base','Geelong Cats'],
  ['79','Lawson Humphries','Base','Geelong Cats'],
  ['80','Gryan Miers','Base','Geelong Cats'],
  ['81','Connor O\'Sullivan','Base','Geelong Cats'],
  ['82','Bailey Smith','Base','Geelong Cats'],
  ['83','Tyson Stengle','Base','Geelong Cats'],
  ['84','Tom Stewart','Base','Geelong Cats'],
  ['85','Lachie Ash','Base','GWS GIANTS'],
  ['86','Stephen Coniglio','Base','GWS GIANTS'],
  ['87','Tom Green','Base','GWS GIANTS'],
  ['88','Harry Himmelberg','Base','GWS GIANTS'],
  ['89','Jesse Hogan','Base','GWS GIANTS'],
  ['90','Connor Idun','Base','GWS GIANTS'],
  ['91','Darcy Jones','Base','GWS GIANTS'],
  ['92','Jake Stringer','Base','GWS GIANTS'],
  ['93','Sam Taylor','Base','GWS GIANTS'],
  ['94','Callan Ward','Base','GWS GIANTS'],
  ['95','Ryan Angwin','Base','GWS GIANTS'],
  ['96','Lachie Whitfield','Base','GWS GIANTS'],
  ['97','Noah Anderson','Base','Gold Coast SUNS'],
  ['98','Sam Collins','Base','Gold Coast SUNS'],
  ['99','Alex Davies','Base','Gold Coast SUNS'],
  ['100','Joel Jeffrey','Base','Gold Coast SUNS'],
  ['101','Ben King','Base','Gold Coast SUNS'],
  ['102','Ben Long','Base','Gold Coast SUNS'],
  ['103','John Noble','Base','Gold Coast SUNS'],
  ['104','Wil Powell','Base','Gold Coast SUNS'],
  ['105','Daniel Rioli','Base','Gold Coast SUNS'],
  ['106','Bodhi Uwland','Base','Gold Coast SUNS'],
  ['107','Jed Walter','Base','Gold Coast SUNS'],
  ['108','Jarrod Witts','Base','Gold Coast SUNS'],
  ['109','Karl Amon','Base','Hawthorn'],
  ['110','Josh Battle','Base','Hawthorn'],
  ['111','Massimo D\'Ambrosio','Base','Hawthorn'],
  ['112','Will Day','Base','Hawthorn'],
  ['113','Jack Ginnivan','Base','Hawthorn'],
  ['114','Jack Gunston','Base','Hawthorn'],
  ['115','Blake Hardwick','Base','Hawthorn'],
  ['116','Jarman Impey','Base','Hawthorn'],
  ['117','Dylan Moore','Base','Hawthorn'],
  ['118','Josh Ward','Base','Hawthorn'],
  ['119','Nick Watson','Base','Hawthorn'],
  ['120','Mitchell Lewis','Base','Hawthorn'],
  ['121','Kade Chandler','Base','Melbourne'],
  ['122','Ed Langdon','Base','Melbourne'],
  ['123','Jake Lever','Base','Melbourne'],
  ['124','Xavier Lindsay','Base','Melbourne'],
  ['125','Steven May','Base','Melbourne'],
  ['126','Tom McDonald','Base','Melbourne'],
  ['127','Caleb Windsor','Base','Melbourne'],
  ['128','Kysaiah Pickett','Base','Melbourne'],
  ['129','Trent Rivers','Base','Melbourne'],
  ['130','Christian Salem','Base','Melbourne'],
  ['131','Tom Sparrow','Base','Melbourne'],
  ['132','Jack Viney','Base','Melbourne'],
  ['133','Charlie Comben','Base','North Melbourne'],
  ['134','Paul Curtis','Base','North Melbourne'],
  ['135','Caleb Daniel','Base','North Melbourne'],
  ['136','Jack Darling','Base','North Melbourne'],
  ['137','Nick Larkey','Base','North Melbourne'],
  ['138','Luke McDonald','Base','North Melbourne'],
  ['139','Colby McKercher','Base','North Melbourne'],
  ['140','Finn O\'Sullivan','Base','North Melbourne'],
  ['141','Luke Parker','Base','North Melbourne'],
  ['142','Tom Powell','Base','North Melbourne'],
  ['143','Tristan Xerri','Base','North Melbourne'],
  ['144','Cameron Zurhaar','Base','North Melbourne'],
  ['145','Aliir Aliir','Base','Port Adelaide'],
  ['146','Miles Bergman','Base','Port Adelaide'],
  ['147','Travis Boak','Base','Port Adelaide'],
  ['148','Kane Farrell','Base','Port Adelaide'],
  ['149','Mitch Georgiades','Base','Port Adelaide'],
  ['150','Jackson Mead','Base','Port Adelaide'],
  ['151','Christian Moraes','Base','Port Adelaide'],
  ['152','Sam Powell-Pepper','Base','Port Adelaide'],
  ['153','Joe Richards','Base','Port Adelaide'],
  ['154','Willie Rioli','Base','Port Adelaide'],
  ['155','Connor Rozee','Base','Port Adelaide'],
  ['156','Ollie Wines','Base','Port Adelaide'],
  ['157','Sam Banks','Base','Richmond'],
  ['158','Nathan Broad','Base','Richmond'],
  ['159','Tom Brown','Base','Richmond'],
  ['160','Thomson Dow','Base','Richmond'],
  ['161','Jacob Hopper','Base','Richmond'],
  ['162','Tom Lynch','Base','Richmond'],
  ['163','Rhyan Mansell','Base','Richmond'],
  ['164','Kamdyn McIntosh','Base','Richmond'],
  ['165','Jack Ross','Base','Richmond'],
  ['166','Jayden Short','Base','Richmond'],
  ['167','Luke Trainor','Base','Richmond'],
  ['168','Nick Vlastuin','Base','Richmond'],
  ['169','Ryan Byrnes','Base','St Kilda'],
  ['170','Anthony Caminiti','Base','St Kilda'],
  ['171','Jack Higgins','Base','St Kilda'],
  ['172','Bradley Hill','Base','St Kilda'],
  ['173','Jack Macrae','Base','St Kilda'],
  ['174','Rowan Marshall','Base','St Kilda'],
  ['175','Mattaes Phillipou','Base','St Kilda'],
  ['176','Cooper Sharman','Base','St Kilda'],
  ['177','Jack Sinclair','Base','St Kilda'],
  ['178','Callum Wilkie','Base','St Kilda'],
  ['179','Darcy Wilson','Base','St Kilda'],
  ['180','Marcus Windhager','Base','St Kilda'],
  ['181','Joel Amarty','Base','Sydney Swans'],
  ['182','Riley Bice','Base','Sydney Swans'],
  ['183','Riley Bice','Base','Sydney Swans'],
  ['184','Nick Blakey','Base','Sydney Swans'],
  ['185','Logan McDonald','Base','Sydney Swans'],
  ['186','Brodie Grundy','Base','Sydney Swans'],
  ['187','Callum Mills','Base','Sydney Swans'],
  ['188','Jake Lloyd','Base','Sydney Swans'],
  ['189','Justin McInerney','Base','Sydney Swans'],
  ['190','Hayden McLean','Base','Sydney Swans'],
  ['191','Dane Rampe','Base','Sydney Swans'],
  ['192','Matt Roberts','Base','Sydney Swans'],
  ['193','James Rowbottom','Base','West Coast Eagles'],
  ['194','Liam Baker','Base','West Coast Eagles'],
  ['195','Tom Cole','Base','West Coast Eagles'],
  ['196','Jamie Cripps','Base','West Coast Eagles'],
  ['197','Liam Duggan','Base','West Coast Eagles'],
  ['198','Jack Graham','Base','West Coast Eagles'],
  ['199','Elijah Hewett','Base','West Coast Eagles'],
  ['200','Brady Hough','Base','West Coast Eagles'],
  ['201','Ryan Maric','Base','West Coast Eagles'],
  ['202','Jeremy McGovern','Base','West Coast Eagles'],
  ['203','Tim Kelly','Base','West Coast Eagles'],
  ['204','Jake Waterman','Base','West Coast Eagles'],
  ['205','Lachlan Bramble','Base','Western Bulldogs'],
  ['206','Bailey Dale','Base','Western Bulldogs'],
  ['207','Tim English','Base','Western Bulldogs'],
  ['208','Joel Freijah','Base','Western Bulldogs'],
  ['209','Matthew Kennedy','Base','Western Bulldogs'],
  ['210','Tom Liberatore','Base','Western Bulldogs'],
  ['211','Aaron Naughton','Base','Western Bulldogs'],
  ['212','Ryley Sanders','Base','Western Bulldogs'],
  ['213','Adam Treloar','Base','Western Bulldogs'],
  ['214','Cody Weightman','Base','Western Bulldogs'],
  ['215','Rhylee West','Base','Western Bulldogs'],
  ['216','Bailey Williams','Base','Western Bulldogs'],
  ['B1','Jordan Dawson','Black','Adelaide Crows'],
  ['B2','Darcy Fogarty','Black','Adelaide Crows'],
  ['B3','Ben Keays','Black','Adelaide Crows'],
  ['B4','Max Michalanney','Black','Adelaide Crows'],
  ['B5','Izak Rankine','Black','Adelaide Crows'],
  ['B6','Jake Soligo','Black','Adelaide Crows'],
  ['B7','Riley Thilthorpe','Black','Adelaide Crows'],
  ['B8','Taylor Walker','Black','Adelaide Crows'],
  ['B9','Levi Ashcroft','Black','Brisbane Lions'],
  ['B10','Will Ashcroft','Black','Brisbane Lions'],
  ['B11','Charlie Cameron','Black','Brisbane Lions'],
  ['B12','Kai Lohmann','Black','Brisbane Lions'],
  ['B13','Hugh McCluggage','Black','Brisbane Lions'],
  ['B14','Lachie Neale','Black','Brisbane Lions'],
  ['B15','Cam Rayner','Black','Brisbane Lions'],
  ['B16','Dayne Zorko','Black','Brisbane Lions'],
  ['B17','Patrick Cripps','Black','Carlton'],
  ['B18','Hudson O\'Keeffe','Black','Carlton'],
  ['B19','Ollie Hollands','Black','Carlton'],
  ['B20','Harry McKay','Black','Carlton'],
  ['B21','Ashton Moir','Black','Carlton'],
  ['B22','Sam Walsh','Black','Carlton'],
  ['B23','Jacob Weitering','Black','Carlton'],
  ['B24','Jacob Weitering','Black','Carlton'],
  ['B25','Jack Crisp','Black','Collingwood'],
  ['B26','Nick Daicos','Black','Collingwood'],
  ['B27','Josh Daicos','Black','Collingwood'],
  ['B28','Jamie Elliott','Black','Collingwood'],
  ['B29','Bobby Hill','Black','Collingwood'],
  ['B30','Ned Long','Black','Collingwood'],
  ['B31','Jordan De Goey','Black','Collingwood'],
  ['B32','Scott Pendlebury','Black','Collingwood'],
  ['B33','Nate Caddy','Black','Essendon'],
  ['B34','Sam Durham','Black','Essendon'],
  ['B35','Isaac Kako','Black','Essendon'],
  ['B36','Kyle Langford','Black','Essendon'],
  ['B37','Nic Martin','Black','Essendon'],
  ['B38','Andrew McGrath','Black','Essendon'],
  ['B39','Zach Merrett','Black','Essendon'],
  ['B40','Darcy Parish','Black','Essendon'],
  ['B41','Jye Amiss','Black','Fremantle'],
  ['B42','Shai Bolton','Black','Fremantle'],
  ['B43','Andrew Brayshaw','Black','Fremantle'],
  ['B44','Luke Jackson','Black','Fremantle'],
  ['B45','Murphy Reid','Black','Fremantle'],
  ['B46','Caleb Serong','Black','Fremantle'],
  ['B47','Josh Treacy','Black','Fremantle'],
  ['B48','Hayden Young','Black','Fremantle'],
  ['B49','Mark Blicavs','Black','Geelong Cats'],
  ['B50','Jeremy Cameron','Black','Geelong Cats'],
  ['B51','Patrick Dangerfield','Black','Geelong Cats'],
  ['B52','Sam De Koning','Black','Geelong Cats'],
  ['B53','Oliver Dempsey','Black','Geelong Cats'],
  ['B54','Max Holmes','Black','Geelong Cats'],
  ['B55','Bailey Smith','Black','Geelong Cats'],
  ['B56','Tom Stewart','Black','Geelong Cats'],
  ['B57','Aaron Cadman','Black','GWS GIANTS'],
  ['B58','Finn Callaghan','Black','GWS GIANTS'],
  ['B59','Tom Green','Black','GWS GIANTS'],
  ['B60','Toby Greene','Black','GWS GIANTS'],
  ['B61','Jesse Hogan','Black','GWS GIANTS'],
  ['B62','Josh Kelly','Black','GWS GIANTS'],
  ['B63','Sam Taylor','Black','GWS GIANTS'],
  ['B64','Lachie Whitfield','Black','GWS GIANTS'],
  ['B65','Noah Anderson','Black','Gold Coast SUNS'],
  ['B66','Mac Andrew','Black','Gold Coast SUNS'],
  ['B67','Bailey Humphrey','Black','Gold Coast SUNS'],
  ['B68','Ben King','Black','Gold Coast SUNS'],
  ['B69','Touk Miller','Black','Gold Coast SUNS'],
  ['B70','Daniel Rioli','Black','Gold Coast SUNS'],
  ['B71','Matt Rowell','Black','Gold Coast SUNS'],
  ['B72','Jed Walter','Black','Gold Coast SUNS'],
  ['B73','Will Day','Black','Hawthorn'],
  ['B74','Jack Gunston','Black','Hawthorn'],
  ['B75','Cam Mackenzie','Black','Hawthorn'],
  ['B76','Jai Newcombe','Black','Hawthorn'],
  ['B77','James Sicily','Black','Hawthorn'],
  ['B78','Nick Watson','Black','Hawthorn'],
  ['B79','Josh Weddle','Black','Hawthorn'],
  ['B80','Connor Macdonald','Black','Hawthorn'],
  ['B81','Max Gawn','Black','Melbourne'],
  ['B82','Harvey Langford','Black','Melbourne'],
  ['B83','Xavier Lindsay','Black','Melbourne'],
  ['B84','Jacob Van Rooyen','Black','Melbourne'],
  ['B85','Jake Lever','Black','Melbourne'],
  ['B86','Kysaiah Pickett','Black','Melbourne'],
  ['B87','Jack Viney','Black','Melbourne'],
  ['B88','Caleb Windsor','Black','Melbourne'],
  ['B89','Luke Davies-Uniacke','Black','North Melbourne'],
  ['B90','Nick Larkey','Black','North Melbourne'],
  ['B91','Colby McKercher','Black','North Melbourne'],
  ['B92','Finn O\'Sullivan','Black','North Melbourne'],
  ['B93','Luke Parker','Black','North Melbourne'],
  ['B94','Harry Sheezel','Black','North Melbourne'],
  ['B95','George Wardlaw','Black','North Melbourne'],
  ['B96','Jy Simpkin','Black','North Melbourne'],
  ['B97','Miles Bergman','Black','Port Adelaide'],
  ['B98','Travis Boak','Black','Port Adelaide'],
  ['B99','Jase Burgoyne','Black','Port Adelaide'],
  ['B100','Zak Butters','Black','Port Adelaide'],
  ['B101','Willem Drew','Black','Port Adelaide'],
  ['B102','Mitch Georgiades','Black','Port Adelaide'],
  ['B103','Jason Horne-Francis','Black','Port Adelaide'],
  ['B104','Commor Rozee','Black','Port Adelaide'],
  ['B105','Nathan Broad','Black','Richmond'],
  ['B106','Tom Brown','Black','Richmond'],
  ['B107','Sam Lalor','Black','Richmond'],
  ['B108','Seth Campbell','Black','Richmond'],
  ['B109','Tom Lynch','Black','Richmond'],
  ['B110','Toby Nankervis','Black','Richmond'],
  ['B111','Tim Taranto','Black','Richmond'],
  ['B112','Nick Vlastuin','Black','Richmond'],
  ['B113','Jack Higgins','Black','St Kilda'],
  ['B114','Max King','Black','St Kilda'],
  ['B115','Jack Macrae','Black','St Kilda'],
  ['B116','Rowan Marshall','Black','St Kilda'],
  ['B117','Mitch Owens','Black','St Kilda'],
  ['B118','Mattaes Phillipou','Black','St Kilda'],
  ['B119','Alix Tauru','Black','St Kilda'],
  ['B120','Nasiah Wanganeen-Milera','Black','St Kilda'],
  ['B121','Nick Blakey','Black','Sydney Swans'],
  ['B122','Errol Gulden','Black','Sydney Swans'],
  ['B123','Tom McCartin','Black','Sydney Swans'],
  ['B124','Isaac Heeney','Black','Sydney Swans'],
  ['B125','Justin McInerney','Black','Sydney Swans'],
  ['B126','Tom Papley','Black','Sydney Swans'],
  ['B127','James Rowbottom','Black','Sydney Swans'],
  ['B128','Chad Warner','Black','Sydney Swans'],
  ['B129','Jack Graham','Black','West Coast Eagles'],
  ['B130','Liam Baker','Black','West Coast Eagles'],
  ['B131','Reuben Ginbey','Black','West Coast Eagles'],
  ['B132','Tim Kelly','Black','West Coast Eagles'],
  ['B133','Jeremy McGovern','Black','West Coast Eagles'],
  ['B134','Harley Reid','Black','West Coast Eagles'],
  ['B135','Bo Allan','Black','West Coast Eagles'],
  ['B136','Jake Waterman','Black','West Coast Eagles'],
  ['B137','Bailey Dale','Black','Western Bulldogs'],
  ['B138','Marcus Bontempelli','Black','Western Bulldogs'],
  ['B139','Sam Darcy','Black','Western Bulldogs'],
  ['B140','Sam Davidson','Black','Western Bulldogs'],
  ['B141','Matthew Kennedy','Black','Western Bulldogs'],
  ['B142','Tom Liberatore','Black','Western Bulldogs'],
  ['B143','Aaron Naughton','Black','Western Bulldogs'],
  ['B144','Ed Richards','Black','Western Bulldogs'],
  ['P1','Sid Draper','Solo Double Patch','Adelaide Crows'],
  ['P2','Rory Laird','Solo Double Patch','Adelaide Crows'],
  ['P3','Reilly O\'Brien','Solo Double Patch','Adelaide Crows'],
  ['P4','Daniel Curtin','Solo Double Patch','Adelaide Crows'],
  ['P5','Riley Thilthorpe','Solo Double Patch','Adelaide Crows'],
  ['P6','Taylor Walker','Solo Double Patch','Adelaide Crows'],
  ['P7','Will Ashcroft','Solo Double Patch','Brisbane Lions'],
  ['P8','Charlie Cameron','Solo Double Patch','Brisbane Lions'],
  ['P9','Jarrod Berry','Solo Double Patch','Brisbane Lions'],
  ['P10','Levi Ashcroft','Solo Double Patch','Brisbane Lions'],
  ['P11','Hugh McCluggage','Solo Double Patch','Brisbane Lions'],
  ['P12','Cam Rayner','Solo Double Patch','Brisbane Lions'],
  ['P13','Adam Cerra','Solo Double Patch','Carlton'],
  ['P14','Sam Walsh','Solo Double Patch','Carlton'],
  ['P15','Marc Murphy','Solo Double Patch','Carlton'],
  ['P16','Harry McKay','Solo Double Patch','Carlton'],
  ['P17','Adam Saad','Solo Double Patch','Carlton'],
  ['P18','Jacob Weitering','Solo Double Patch','Carlton'],
  ['P19','Jordan De Goey','Solo Double Patch','Collingwood'],
  ['P20','Jamie Elliott','Solo Double Patch','Collingwood'],
  ['P21','Bobby Hill','Solo Double Patch','Collingwood'],
  ['P22','Dan Houston','Solo Double Patch','Collingwood'],
  ['P23','Jeremy Howe','Solo Double Patch','Collingwood'],
  ['P24','Josh Daicos','Solo Double Patch','Collingwood'],
  ['P25','Nate Caddy','Solo Double Patch','Essendon'],
  ['P26','Kyle Langford','Solo Double Patch','Essendon'],
  ['P27','Dyson Heppell','Solo Double Patch','Essendon'],
  ['P28','Andrew McGrath','Solo Double Patch','Essendon'],
  ['P29','Zach Merrett','Solo Double Patch','Essendon'],
  ['P30','Archie Perkins','Solo Double Patch','Essendon'],
  ['P31','Jye Amiss','Solo Double Patch','Fremantle'],
  ['P32','Shai Bolton','Solo Double Patch','Fremantle'],
  ['P33','Alex Pearce','Solo Double Patch','Fremantle'],
  ['P34','Josh Treacy','Solo Double Patch','Fremantle'],
  ['P35','Michael Walters','Solo Double Patch','Fremantle'],
  ['P36','Fremantle Dockers Redemption','Solo Double Patch','Fremantle'],
  ['P37','Tom Hawkins','Solo Double Patch','Geelong Cats'],
  ['P38','Mitch Duncan','Solo Double Patch','Geelong Cats'],
  ['P39','Jack Henry','Solo Double Patch','Geelong Cats'],
  ['P40','Shannon Neale','Solo Double Patch','Geelong Cats'],
  ['P41','Tyson Stengle','Solo Double Patch','Geelong Cats'],
  ['P42','Tom Stewart','Solo Double Patch','Geelong Cats'],
  ['P43','Toby Bedford','Solo Double Patch','GWS GIANTS'],
  ['P44','Aaron Cadman','Solo Double Patch','GWS GIANTS'],
  ['P45','Finn Callaghan','Solo Double Patch','GWS GIANTS'],
  ['P46','Stephen Coniglio','Solo Double Patch','GWS GIANTS'],
  ['P47','Tom Green','Solo Double Patch','GWS GIANTS'],
  ['P48','Giants Redemption','Solo Double Patch','GWS GIANTS'],
  ['P49','Ben King','Solo Double Patch','Gold Coast SUNS'],
  ['P50','Gold Coast Suns Redemption','Solo Double Patch','Gold Coast SUNS'],
  ['P51','Touk Miller','Solo Double Patch','Gold Coast SUNS'],
  ['P52','Daniel Rioli','Solo Double Patch','Gold Coast SUNS'],
  ['P53','David Swallow','Solo Double Patch','Gold Coast SUNS'],
  ['P54','Jed Walter','Solo Double Patch','Gold Coast SUNS'],
  ['P55','Massimo D\'Ambrosio','Solo Double Patch','Hawthorn'],
  ['P56','Nick Watson','Solo Double Patch','Hawthorn'],
  ['P57','Cam Mackenzie','Solo Double Patch','Hawthorn'],
  ['P58','Josh Weddle','Solo Double Patch','Hawthorn'],
  ['P59','Jai Newcombe','Solo Double Patch','Hawthorn'],
  ['P60','Calsher Dear','Solo Double Patch','Hawthorn'],
  ['P61','Max Gawn','Solo Double Patch','Melbourne'],
  ['P62','Harvey Langford','Solo Double Patch','Melbourne'],
  ['P63','Xavier Lindsay','Solo Double Patch','Melbourne'],
  ['P64','Bayley Fritsch','Solo Double Patch','Melbourne'],
  ['P65','Jack Viney','Solo Double Patch','Melbourne'],
  ['P66','Caleb Windsor','Solo Double Patch','Melbourne'],
  ['P67','Finn O\'Sullivan','Solo Double Patch','North Melbourne'],
  ['P68','Will Phillips','Solo Double Patch','North Melbourne'],
  ['P69','Bailey Scott','Solo Double Patch','North Melbourne'],
  ['P70','JJ Simpkin','Solo Double Patch','North Melbourne'],
  ['P71','George Wardlaw','Solo Double Patch','North Melbourne'],
  ['P72','Cameron Zurhaar','Solo Double Patch','North Melbourne'],
  ['P73','Miles Bergman','Solo Double Patch','Port Adelaide'],
  ['P74','Port Adelaide Redemption A','Solo Double Patch','Port Adelaide'],
  ['P75','Port Adelaide Redemption B','Solo Double Patch','Port Adelaide'],
  ['P76','Port Adelaide Redemption C','Solo Double Patch','Port Adelaide'],
  ['P77','Port Adelaide Redemption D','Solo Double Patch','Port Adelaide'],
  ['P78','Port Adelaide Redemption E','Solo Double Patch','Port Adelaide'],
  ['P79','Nathan Broad','Solo Double Patch','Richmond'],
  ['P80','Seth Campbell','Solo Double Patch','Richmond'],
  ['P81','Sam Lalor','Solo Double Patch','Richmond'],
  ['P82','Toby Nankervis','Solo Double Patch','Richmond'],
  ['P83','Dion Prestia','Solo Double Patch','Richmond'],
  ['P84','Nick Vlastuin','Solo Double Patch','Richmond'],
  ['P85','Jack Macrae','Solo Double Patch','St Kilda'],
  ['P86','Mitch Owens','Solo Double Patch','St Kilda'],
  ['P87','Mattaes Phillipou','Solo Double Patch','St Kilda'],
  ['P88','Jack Sinclair','Solo Double Patch','St Kilda'],
  ['P89','Nasiah Wanganeen-Milera','Solo Double Patch','St Kilda'],
  ['P90','Darcy Wilson','Solo Double Patch','St Kilda'],
  ['P91','Sydney Swans Redemption A','Solo Double Patch','Sydney Swans'],
  ['P92','Joel Amartey','Solo Double Patch','Sydney Swans'],
  ['P93','Isaac Heeney','Solo Double Patch','Sydney Swans'],
  ['P94','Tom McCartin','Solo Double Patch','Sydney Swans'],
  ['P95','Sydney Swans Redemption B','Solo Double Patch','Sydney Swans'],
  ['P96','Chad Warner','Solo Double Patch','Sydney Swans'],
  ['P97','West Coast Eagles Redemption A','Solo Double Patch','West Coast Eagles'],
  ['P98','Liam Baker','Solo Double Patch','West Coast Eagles'],
  ['P99','West Coast Eagles Redemption B','Solo Double Patch','West Coast Eagles'],
  ['P100','West Coast Eagles Redemption C','Solo Double Patch','West Coast Eagles'],
  ['P101','Brady Hough','Solo Double Patch','West Coast Eagles'],
  ['P102','Harley Reid','Solo Double Patch','West Coast Eagles'],
  ['P103','Marcus Bontempelli','Solo Double Patch','Western Bulldogs'],
  ['P104','Tim English','Solo Double Patch','Western Bulldogs'],
  ['P105','Tom Liberatore','Solo Double Patch','Western Bulldogs'],
  ['P106','Sam Darcy','Solo Double Patch','Western Bulldogs'],
  ['P107','Cody Weightman','Solo Double Patch','Western Bulldogs'],
  ['P108','Rhylee West','Solo Double Patch','Western Bulldogs'],
  ['DP1','Jordan Dawson / Daniel Curtin','Dual Patch','Adelaide Crows'],
  ['DP2','Sid Draper / Rory Sloane','Dual Patch','Adelaide Crows'],
  ['DP3','Reilly O\'Brien / Riley Thilthorpe','Dual Patch','Adelaide Crows'],
  ['DP4','Will Ashcroft / Hugh McCluggage','Dual Patch','Brisbane Lions'],
  ['DP5','Charlie Cameron / Cam Rayner','Dual Patch','Brisbane Lions'],
  ['DP6','Josh Dunkley / Levi Ashcroft','Dual Patch','Brisbane Lions'],
  ['DP7','Adam Cerra / Sam Walsh','Dual Patch','Carlton'],
  ['DP8','Patrick Cripps / Chris Judd','Dual Patch','Carlton'],
  ['DP9','Jacob Weitering / Harry McKay','Dual Patch','Carlton'],
  ['DP10','Nick Daicos / Bobby Hill','Dual Patch','Collingwood'],
  ['DP11','Jamie Elliott / Josh Daicos','Dual Patch','Collingwood'],
  ['DP12','Dan Houston / Brayden Maynard','Dual Patch','Collingwood'],
  ['DP13','James Hird / Zach Merrett','Dual Patch','Essendon'],
  ['DP14','Nate Caddy / Kyle Langford','Dual Patch','Essendon'],
  ['DP15','Dyson Heppell / Andrew McGrath','Dual Patch','Essendon'],
  ['DP16','Jye Amiss / Josh Treacy','Dual Patch','Fremantle'],
  ['DP17','Shai Bolton / Michael Walters','Dual Patch','Fremantle'],
  ['DP18','Andrew Brayshaw / Nat Fyfe','Dual Patch','Fremantle'],
  ['DP19','Jeremy Cameron / Patrick Dangerfield','Dual Patch','Geelong Cats'],
  ['DP20','Mark Blicavs / Max Holmes','Dual Patch','Geelong Cats'],
  ['DP21','Mitch Duncan / Tom Stewart','Dual Patch','Geelong Cats'],
  ['DP22','Josh Kelly / Callan Ward','Dual Patch','GWS GIANTS'],
  ['DP23','Tom Green / Sam Taylor','Dual Patch','GWS GIANTS'],
  ['DP24','Toby Bedford / Aaron Cadman','Dual Patch','GWS GIANTS'],
  ['DP25','Gary Ablett Jnr / Daniel Rioli','Dual Patch','Gold Coast SUNS'],
  ['DP26','Bailey Humphrey / Ben King','Dual Patch','Gold Coast SUNS'],
  ['DP27','Touk Miller / Matt Rowell','Dual Patch','Gold Coast SUNS'],
  ['DP28','Dylan Moore / Jack Ginnivan','Dual Patch','Hawthorn'],
  ['DP29','Will Day / Josh Weddle','Dual Patch','Hawthorn'],
  ['DP30','Cam Mackenzie / Nick Watson','Dual Patch','Hawthorn'],
  ['DP31','Max Gawn / Steven May','Dual Patch','Melbourne'],
  ['DP32','Caleb Windsor / Jack Viney','Dual Patch','Melbourne'],
  ['DP33','Harvey Langford / Xavier Lindsay','Dual Patch','Melbourne'],
  ['DP34','Nick Larkey / Cameron Zurhaar','Dual Patch','North Melbourne'],
  ['DP35','Luke Davies-Uniacke / Jy Simpkin','Dual Patch','North Melbourne'],
  ['DP36','Finn O\'Sullivan / George Wardlaw','Dual Patch','North Melbourne'],
  ['DP37','Redemption Set A','Dual Patch','Port Adelaide'],
  ['DP38','Redemption Set B','Dual Patch','Port Adelaide'],
  ['DP39','Redemption Set C','Dual Patch','Port Adelaide'],
  ['DP40','Seth Campbell / Sam Lalor','Dual Patch','Richmond'],
  ['DP41','Nathan Broad / Dion Prestia','Dual Patch','Richmond'],
  ['DP42','Alex Rance / Nick Vlastuin','Dual Patch','Richmond'],
  ['DP43','Jack Macrae / Nathan Burke','Dual Patch','St Kilda'],
  ['DP44','Nasiah Wanganeen-Milera / Darcy Wilson','Dual Patch','St Kilda'],
  ['DP45','Mitch Owens / Mattaes Phillipou','Dual Patch','St Kilda'],
  ['DP46','Joel Amartey / Isaac Heeney','Dual Patch','Sydney Swans'],
  ['DP47','Tom McCartin / Tom Papley','Dual Patch','Sydney Swans'],
  ['DP48','James Rowbottom / Chad Warner','Dual Patch','Sydney Swans'],
  ['DP49','Liam Baker / Elliott Yeo','Dual Patch','West Coast Eagles'],
  ['DP50','Redemption Set A','Dual Patch','West Coast Eagles'],
  ['DP51','Redemption Set B','Dual Patch','West Coast Eagles'],
  ['DP52','Cody Weightman / Rhylee West','Dual Patch','Western Bulldogs'],
  ['DP53','Aaron Naughton / Sam Darcy','Dual Patch','Western Bulldogs'],
  ['DP54','Marcus Bontempelli / Tim English','Dual Patch','Western Bulldogs'],
  ['TMB1','Adelaide Crows','Team Multi-Patch','Adelaide Crows'],
  ['TMB2','Brisbane Lions','Team Multi-Patch','Brisbane Lions'],
  ['TMB3','Carlton','Team Multi-Patch','Carlton'],
  ['TMB4','Collingwood','Team Multi-Patch','Collingwood'],
  ['TMB5','Essendon','Team Multi-Patch','Essendon'],
  ['TMB6','Fremantle','Team Multi-Patch','Fremantle'],
  ['TMB7','Geelong Cats','Team Multi-Patch','Geelong Cats'],
  ['TMB8','Gold Coast SUNS','Team Multi-Patch','Gold Coast SUNS'],
  ['TMB9','GWS GIANTS','Team Multi-Patch','GWS GIANTS'],
  ['TMB10','Hawthorn','Team Multi-Patch','Hawthorn'],
  ['TMB11','Melbourne','Team Multi-Patch','Melbourne'],
  ['TMB12','North Melbourne','Team Multi-Patch','North Melbourne'],
  ['TMB13','Port Adelaide','Team Multi-Patch','Port Adelaide'],
  ['TMB14','Richmond','Team Multi-Patch','Richmond'],
  ['TMB15','St Kilda','Team Multi-Patch','St Kilda'],
  ['TMB16','Sydney Swans','Team Multi-Patch','Sydney Swans'],
  ['TMB17','West Coast Eagles','Team Multi-Patch','West Coast Eagles'],
  ['TMB18','Western Bulldogs','Team Multi-Patch','Western Bulldogs'],
  ['JP1','Taylor Walker','Jumbo Patch','Adelaide Crows'],
  ['JP2','Daniel Curtin','Jumbo Patch','Adelaide Crows'],
  ['JP3','Charlie Cameron','Jumbo Patch','Brisbane Lions'],
  ['JP4','Hugh McCluggage','Jumbo Patch','Brisbane Lions'],
  ['JP5','Jacob Weitering','Jumbo Patch','Carlton'],
  ['JP6','Harry McKay','Jumbo Patch','Carlton'],
  ['JP7','Jordan De Goey','Jumbo Patch','Collingwood'],
  ['JP8','Brayden Maynard','Jumbo Patch','Collingwood'],
  ['JP9','Darcy Parish','Jumbo Patch','Essendon'],
  ['JP10','Archie Perkins','Jumbo Patch','Essendon'],
  ['JP11','Alex Pearce','Jumbo Patch','Fremantle'],
  ['JP12','Caleb Serong','Jumbo Patch','Fremantle'],
  ['JP13','Tyson Stengle','Jumbo Patch','Geelong Cats'],
  ['JP14','Tom Stewart','Jumbo Patch','Geelong Cats'],
  ['JP15','Finn Callaghan','Jumbo Patch','GWS GIANTS'],
  ['JP16','Giants Redemption','Jumbo Patch','GWS GIANTS'],
  ['JP17','Noah Anderson','Jumbo Patch','Gold Coast SUNS'],
  ['JP18','Gold Coast Suns Redemption','Jumbo Patch','Gold Coast SUNS'],
  ['JP19','Cam Mackenzie','Jumbo Patch','Hawthorn'],
  ['JP20','Jai Newcombe','Jumbo Patch','Hawthorn'],
  ['JP21','Kysaiah Pickett','Jumbo Patch','Melbourne'],
  ['JP22','Caleb Windsor','Jumbo Patch','Melbourne'],
  ['JP23','Harry Sheezel','Jumbo Patch','North Melbourne'],
  ['JP24','Cameron Zurhaar','Jumbo Patch','North Melbourne'],
  ['JP25','Miles Bergman','Jumbo Patch','Port Adelaide'],
  ['JP26','Zak Butters','Jumbo Patch','Port Adelaide'],
  ['JP27','Sam Lalor','Jumbo Patch','Richmond'],
  ['JP28','Tim Taranto','Jumbo Patch','Richmond'],
  ['JP29','Rowan Marshall','Jumbo Patch','St Kilda'],
  ['JP30','Jack Sinclair','Jumbo Patch','St Kilda'],
  ['JP31','Tom Papley','Jumbo Patch','Sydney Swans'],
  ['JP32','James Rowbottom','Jumbo Patch','Sydney Swans'],
  ['JP33','Luke Shuey','Jumbo Patch','West Coast Eagles'],
  ['JP34','Harley Reid','Jumbo Patch','West Coast Eagles'],
  ['JP35','Aaron Naughton','Jumbo Patch','Western Bulldogs'],
  ['JP36','Cody Weightman','Jumbo Patch','Western Bulldogs'],
  ['RS1','Sam Lalor','Rookie Badge Signature','Richmond'],
  ['RS2','Jagga Smith','Rookie Badge Signature','Carlton'],
  ['RS3','Finn O\'Sullivan','Rookie Badge Signature','North Melbourne'],
  ['RS4','Sid Draper','Rookie Badge Signature','Adelaide Crows'],
  ['RS5','Levi Ashcroft','Rookie Badge Signature','Brisbane Lions'],
  ['RS6','Harvey Langford','Rookie Badge Signature','Melbourne'],
  ['RS7','Josh Smillie','Rookie Badge Signature','Richmond'],
  ['RS8','Tobie Travaglia','Rookie Badge Signature','St Kilda'],
  ['RS9','Alix Tauru','Rookie Badge Signature','St Kilda'],
  ['RS10','Leo Lombard','Rookie Badge Signature','Gold Coast SUNS'],
  ['RS11','Xavier Lindsay','Rookie Badge Signature','Melbourne'],
  ['RS12','Taj Hotton','Rookie Badge Signature','Richmond'],
  ['RS13','Isaac Kako','Rookie Badge Signature','Essendon'],
  ['RS14','Jonty Faull','Rookie Badge Signature','Richmond'],
  ['RS15','Joe Berry','Rookie Badge Signature','Port Adelaide'],
  ['RS16','Bo Allan','Rookie Badge Signature','West Coast Eagles'],
  ['RS17','Murphy Reid','Rookie Badge Signature','Fremantle'],
  ['RS18','Oliver Hannaford','Rookie Badge Signature','GWS GIANTS'],
  ['RS19','Harrison Oliver','Rookie Badge Signature','GWS GIANTS'],
  ['RS20','Cooper Hynes','Rookie Badge Signature','Western Bulldogs'],
  ['RS21','Luke Trainor','Rookie Badge Signature','Richmond'],
  ['RS22','Jesse Dattoli','Rookie Badge Signature','Sydney Swans'],
  ['RS23','Harry Armstrong','Rookie Badge Signature','Richmond'],
  ['RS24','Cody Angove','Rookie Badge Signature','GWS GIANTS'],
  ['RS25','Sam Marshall','Rookie Badge Signature','Brisbane Lions'],
  ['RS26','Ned Bowman','Rookie Badge Signature','Sydney Swans'],
  ['RS27','Matt Whitlock','Rookie Badge Signature','North Melbourne'],
  ['RS28','Thomas Sims','Rookie Badge Signature','Richmond'],
  ['RS29','Lachie Jaques','Rookie Badge Signature','Western Bulldogs'],
  ['RS30','Jobe Shanahan','Rookie Badge Signature','West Coast Eagles'],
  ['RS31','Josh Dolan','Rookie Badge Signature','Western Bulldogs'],
  ['RS32','James Barrat','Rookie Badge Signature','St Kilda'],
  ['RS33','Jack Whitlock','Rookie Badge Signature','Port Adelaide'],
  ['RS34','Charlie Nicholls','Rookie Badge Signature','Fremantle'],
  ['RS35','Noah Mraz','Rookie Badge Signature','Hawthorn'],
  ['RS36','Jack Ough','Rookie Badge Signature','GWS GIANTS'],
  ['RS37','Kayle Gerreyn','Rookie Badge Signature','Essendon'],
  ['RS38','Christian Moraes','Rookie Badge Signature','Port Adelaide'],
  ['RS39','Angus Clarke','Rookie Badge Signature','Essendon'],
  ['RS40','Harry O\'Farrell','Rookie Badge Signature','Carlton'],
  ['RS41','Riley Bice','Rookie Badge Signature','Sydney Swans'],
  ['RS42','Ty Gallop','Rookie Badge Signature','Brisbane Lions'],
  ['RS43','Ben Camporeale','Rookie Badge Signature','Carlton'],
  ['RS44','Jay Polkinghorne','Rookie Badge Signature','Geelong Cats'],
  ['RS45','Hugh Boxshall','Rookie Badge Signature','St Kilda'],
  ['RS46','Tom Gross','Rookie Badge Signature','West Coast Eagles'],
  ['RS47','Joel Cochran','Rookie Badge Signature','Collingwood'],
  ['RS48','Lucca Grego','Rookie Badge Signature','West Coast Eagles'],
  ['RS49','Cooper Bell','Rookie Badge Signature','Gold Coast SUNS'],
  ['RS50','Charlie West','Rookie Badge Signature','Collingwood'],
  ['RS51','Sam Davidson','Rookie Badge Signature','Western Bulldogs'],
  ['RS52','Jacob Molier','Rookie Badge Signature','Geelong Cats'],
  ['RS53','Alex Dodson','Rookie Badge Signature','St Kilda'],
  ['RS54','Lucas Camporeale','Rookie Badge Signature','Carlton'],
  ['RS55','Riak Andrew','Rookie Badge Signature','Sydney Swans'],
  ['RS56','Will Hayes','Rookie Badge Signature','Collingwood'],
  ['RS57','Luke Urquhart','Rookie Badge Signature','North Melbourne'],
  ['RS58','Jasper Alger','Rookie Badge Signature','Richmond'],
  ['RS59','Tyler Welsh','Rookie Badge Signature','Adelaide Crows'],
  ['RS60','Patrick Said','Rookie Badge Signature','St Kilda'],
  ['RS61','Rhys Unwin','Rookie Badge Signature','Essendon'],
  ['RSG1','Sid Draper','Rookie Badge Signature Gold','Adelaide Crows'],
  ['RSG2','Levi Ashcroft','Rookie Badge Signature Gold','Brisbane Lions'],
  ['RSG3','Jagga Smith','Rookie Badge Signature Gold','Carlton'],
  ['RSG4','Will Hayes','Rookie Badge Signature Gold','Collingwood'],
  ['RSG5','Isaac Kako','Rookie Badge Signature Gold','Essendon'],
  ['RSG6','Murphy Reid','Rookie Badge Signature Gold','Fremantle'],
  ['RSG7','Jay Polkinghorne','Rookie Badge Signature Gold','Geelong Cats'],
  ['RSG8','Cody Angove','Rookie Badge Signature Gold','GWS GIANTS'],
  ['RSG9','Leo Lombard','Rookie Badge Signature Gold','Gold Coast SUNS'],
  ['RSG10','Noah Mraz','Rookie Badge Signature Gold','Hawthorn'],
  ['RSG11','Harvey Langford','Rookie Badge Signature Gold','Melbourne'],
  ['RSG12','Finn O\'Sullivan','Rookie Badge Signature Gold','North Melbourne'],
  ['RSG13','Christian Moraes','Rookie Badge Signature Gold','Port Adelaide'],
  ['RSG14','Sam Lalor','Rookie Badge Signature Gold','Richmond'],
  ['RSG15','Tobie Travaglia','Rookie Badge Signature Gold','St Kilda'],
  ['RSG16','Riley Bice','Rookie Badge Signature Gold','Sydney Swans'],
  ['RSG17','Tom Gross','Rookie Badge Signature Gold','West Coast Eagles'],
  ['RSG18','Sam Davidson','Rookie Badge Signature Gold','Western Bulldogs'],
  ['AS1','Ben Keays','AFL Badge Signature','Adelaide Crows'],
  ['AS2','Josh Rachele','AFL Badge Signature','Adelaide Crows'],
  ['AS3','Izak Rankine','AFL Badge Signature','Adelaide Crows'],
  ['AS4','Zac Bailey','AFL Badge Signature','Brisbane Lions'],
  ['AS5','Darcy Wilmot','AFL Badge Signature','Brisbane Lions'],
  ['AS6','Dayne Zorko','AFL Badge Signature','Brisbane Lions'],
  ['AS7','George Hewett','AFL Badge Signature','Carlton'],
  ['AS8','Cooper Lord','AFL Badge Signature','Carlton'],
  ['AS9','Ollie Hollands','AFL Badge Signature','Carlton'],
  ['AS10','Jack Crisp','AFL Badge Signature','Collingwood'],
  ['AS11','Josh Daicos','AFL Badge Signature','Collingwood'],
  ['AS12','Darcy Cameron','AFL Badge Signature','Collingwood'],
  ['AS13','Jye Caldwell','AFL Badge Signature','Essendon'],
  ['AS14','Nic Martin','AFL Badge Signature','Essendon'],
  ['AS15','Zach Reid','AFL Badge Signature','Essendon'],
  ['AS16','Luke Jackson','AFL Badge Signature','Fremantle'],
  ['AS17','Matthew Johnson','AFL Badge Signature','Fremantle'],
  ['AS18','Luke Ryan','AFL Badge Signature','Fremantle'],
  ['AS19','Sam De Koning','AFL Badge Signature','Geelong Cats'],
  ['AS20','Shaun Mannagh','AFL Badge Signature','Geelong Cats'],
  ['AS21','Bailey Smith','AFL Badge Signature','Geelong Cats'],
  ['AS22','Lachie Ash','AFL Badge Signature','Gold Coast SUNS'],
  ['AS23','Toby Greene','AFL Badge Signature','Gold Coast SUNS'],
  ['AS24','Jesse Hogan','AFL Badge Signature','Gold Coast SUNS'],
  ['AS25','Mac Andrew','AFL Badge Signature','GWS GIANTS'],
  ['AS26','Jed Walter','AFL Badge Signature','GWS GIANTS'],
  ['AS27','Ben Long','AFL Badge Signature','GWS GIANTS'],
  ['AS28','Karl Amon','AFL Badge Signature','Hawthorn'],
  ['AS29','Jack Gunston','AFL Badge Signature','Hawthorn'],
  ['AS30','James Sicily','AFL Badge Signature','Hawthorn'],
  ['AS31','Kade Chandler','AFL Badge Signature','Melbourne'],
  ['AS32','Jake Lever','AFL Badge Signature','Melbourne'],
  ['AS33','Christian Salem','AFL Badge Signature','Melbourne'],
  ['AS34','Paul Curtis','AFL Badge Signature','North Melbourne'],
  ['AS35','Colby McKercher','AFL Badge Signature','North Melbourne'],
  ['AS36','Tom Powell','AFL Badge Signature','North Melbourne'],
  ['AS37','Willem Drew','AFL Badge Signature','Port Adelaide'],
  ['AS38','Kane Farrell','AFL Badge Signature','Port Adelaide'],
  ['AS39','Darcy Byrne-Jones','AFL Badge Signature','Port Adelaide'],
  ['AS40','Jacob Hopper','AFL Badge Signature','Richmond'],
  ['AS41','Jayden Short','AFL Badge Signature','Richmond'],
  ['AS42','Tom Lynch','AFL Badge Signature','Richmond'],
  ['AS43','Jack Higgins','AFL Badge Signature','St Kilda'],
  ['AS44','Cooper Sharman','AFL Badge Signature','St Kilda'],
  ['AS45','Marcus Windhager','AFL Badge Signature','St Kilda'],
  ['AS46','Errol Gulden','AFL Badge Signature','Sydney Swans'],
  ['AS47','Justin McInerney','AFL Badge Signature','Sydney Swans'],
  ['AS48','Callum Mills','AFL Badge Signature','Sydney Swans'],
  ['AS49','Jack Graham','AFL Badge Signature','West Coast Eagles'],
  ['AS50','Jeremy McGovern','AFL Badge Signature','West Coast Eagles'],
  ['AS51','Jake Waterman','AFL Badge Signature','West Coast Eagles'],
  ['AS52','Bailey Dale','AFL Badge Signature','Western Bulldogs'],
  ['AS53','Matthew Kennedy','AFL Badge Signature','Western Bulldogs'],
  ['AS54','Ed Richards','AFL Badge Signature','Western Bulldogs'],
  ['PS1','Riley Thilthorpe','Patch Signature','Adelaide Crows'],
  ['PS2','Cam Rayner','Patch Signature','Brisbane Lions'],
  ['PS3','Marc Murphy','Patch Signature','Carlton'],
  ['PS4','Adam Cerra','Patch Signature','Carlton'],
  ['PS5','Bobby Hill','Patch Signature','Collingwood'],
  ['PS6','Dan Houston','Patch Signature','Collingwood'],
  ['PS7','Kyle Langford','Patch Signature','Essendon'],
  ['PS8','Andrew McGrath','Patch Signature','Essendon'],
  ['PS9','Josh Treacy','Patch Signature','Fremantle'],
  ['PS10','Mark Blicavs','Patch Signature','Geelong Cats'],
  ['PS11','Max Holmes','Patch Signature','Geelong Cats'],
  ['PS12','Tom Green','Patch Signature','GWS GIANTS'],
  ['PS13','Ben King','Patch Signature','Gold Coast SUNS'],
  ['PS14','Dylan Moore','Patch Signature','Hawthorn'],
  ['PS15','Nick Watson','Patch Signature','Hawthorn'],
  ['PS16','Steven May','Patch Signature','Melbourne'],
  ['PS17','George Wardlaw','Patch Signature','North Melbourne'],
  ['PS18','Port Adelaide Redemption','Patch Signature','Port Adelaide'],
  ['PS19','Toby Nankervis','Patch Signature','Richmond'],
  ['PS20','Seth Campbell','Patch Signature','Richmond'],
  ['PS21','Mattaes Phillipou','Patch Signature','St Kilda'],
  ['PS22','Tom Papley','Patch Signature','Sydney Swans'],
  ['PS23','Liam Baker','Patch Signature','West Coast Eagles'],
  ['PS24','Aaron Naughton','Patch Signature','Western Bulldogs'],
  ['PSB1','Jordan Dawson / Rory Sloane','Dual Patch Signature Booklet','Adelaide Crows'],
  ['PSB2','Riley Thilthorpe / Taylor Walker','Dual Patch Signature Booklet','Adelaide Crows'],
  ['PSB3','Will Ashcroft / Levi Ashcroft','Dual Patch Signature Booklet','Brisbane Lions'],
  ['PSB4','Patrick Cripps / Sam Walsh','Dual Patch Signature Booklet','Carlton'],
  ['PSB5','Chris Judd / Jacob Weitering','Dual Patch Signature Booklet','Carlton'],
  ['PSB6','Nick Daicos / Scott Pendlebury','Dual Patch Signature Booklet','Collingwood'],
  ['PSB7','Jordan De Goey / Steele Sidebottom','Dual Patch Signature Booklet','Collingwood'],
  ['PSB8','Zach Merrett / Darcy Parish','Dual Patch Signature Booklet','Essendon'],
  ['PSB9','Nate Caddy / James Hird','Dual Patch Signature Booklet','Essendon'],
  ['PSB10','Andrew Brayshaw / Caleb Serong','Dual Patch Signature Booklet','Fremantle'],
  ['PSB11','Patrick Dangerfield / Tom Hawkins','Dual Patch Signature Booklet','Geelong Cats'],
  ['PSB12','Mark Blicavs / Jeremy Cameron','Dual Patch Signature Booklet','Geelong Cats'],
  ['PSB13','Finn Callaghan / Callan Ward','Dual Patch Signature Booklet','GWS GIANTS'],
  ['PSB14','Matt Rowell / Touk Miller','Dual Patch Signature Booklet','Gold Coast SUNS'],
  ['PSB15','Will Day / Jai Newcombe','Dual Patch Signature Booklet','Hawthorn'],
  ['PSB16','Jack Ginnivan / Josh Weddle','Dual Patch Signature Booklet','Hawthorn'],
  ['PSB17','Max Gawn / Jack Viney','Dual Patch Signature Booklet','Melbourne'],
  ['PSB18','Nick Larkey / Harry Sheezel','Dual Patch Signature Booklet','North Melbourne'],
  ['PSB19','Zak Butters / Jason Horne-Francis','Dual Patch Signature Booklet','Port Adelaide'],
  ['PSB20','Trent Cotchin / Jack Riewoldt','Dual Patch Signature Booklet','Richmond'],
  ['PSB21','Tim Taranto / Nick Vlastuin','Dual Patch Signature Booklet','Richmond'],
  ['PSB22','Robery Harvey / Mitch Owens','Dual Patch Signature Booklet','St Kilda'],
  ['PSB23','Darcy Wilson / Nasiah Wanganeen-Milera','Dual Patch Signature Booklet','St Kilda'],
  ['PSB24','Isaac Heeney / Chad Warner','Dual Patch Signature Booklet','Sydney Swans'],
  ['PSB25','Elliot Yeo / Josh Kennedy','Dual Patch Signature Booklet','West Coast Eagles'],
  ['PSB26','Harley Reid / Luke Shuey','Dual Patch Signature Booklet','West Coast Eagles'],
  ['PSB27','Aaron Naughton / Tom Liberatore','Dual Patch Signature Booklet','Western Bulldogs'],
  ['MP1','Taylor Walker / Lachie Neale / Patrick Cripps / Nick Daicos / Zach Merrett / Nat Fyfe / Patrick Dangerfield / Tom Green / Matt Rowell / Will Day / Max Gawn / Harry Sheezel / Connor Rozee / Tim Taranto / Nasiah Wanganeen-Milera / Isaac Heeney / Harley Reid / Marcus Bontempeli','Mega Patch','']
];
