// ---- Supremacy 2024 ----

registerSet("supremacy-2024", {
  label:   "Supremacy 2024",
  year:    "2024",
  series:  "Supremacy",
  subsets: [
    "Gold",
    "Blue Portrait",
    "Black Pearl",
    "Franchise Future",
    "Franchise Future Signature",
    "Franchise Greats",
    "Franchise Greats Signature",
    "Franchise Greats Dual Signature",
    "Superstar Patch",
    "Triple Superstar Patch",
    "Superstar Patch Signature Booklet",
    "Career Games",
    "Career Games Signature",
    "Premiership Glory",
    "Premiership Glory Signature",
    "Premiership Glory Redemption",
    "Goalkicking Greats",
    "Goalkicking Greats Signature",
    "Goalkicking Greats Dual Signature",
    "1000 Goalkicker Signature",
    "Club Captains",
    "Club Captains Redemption",
    "Captain Signature",
    "Evolution",
    "Evolution Signature",
    "Prem Player Coach Signature",
    "Premiership Brownlow Double Signature",
    "Longest Serving Captains Signature",
  ],
  badge: {
    "Gold": "b-s24-g",
    "Blue Portrait": "b-s24-bp",
    "Black Pearl": "b-s24-bk",
    "Franchise Future": "b-s24-ff",
    "Franchise Future Signature": "b-s24-ffs",
    "Franchise Greats": "b-s24-fg",
    "Franchise Greats Signature": "b-s24-fgs",
    "Franchise Greats Dual Signature": "b-s24-fgds",
    "Superstar Patch": "b-s24-sp",
    "Triple Superstar Patch": "b-s24-tp",
    "Superstar Patch Signature Booklet": "b-s24-sps",
    "Career Games": "b-s24-cg",
    "Career Games Signature": "b-s24-cgs",
    "Premiership Glory": "b-s24-pg",
    "Premiership Glory Signature": "b-s24-pgs",
    "Premiership Glory Redemption": "b-s24-pgr",
    "Goalkicking Greats": "b-s24-gg",
    "Goalkicking Greats Signature": "b-s24-ggs",
    "Goalkicking Greats Dual Signature": "b-s24-ggds",
    "1000 Goalkicker Signature": "b-s24-gks",
    "Club Captains": "b-s24-c",
    "Club Captains Redemption": "b-s24-cr",
    "Captain Signature": "b-s24-cs",
    "Evolution": "b-s24-e",
    "Evolution Signature": "b-s24-es",
    "Prem Player Coach Signature": "b-s24-ppcs",
    "Premiership Brownlow Double Signature": "b-s24-pbds",
    "Longest Serving Captains Signature": "b-s24-lscs",
  },
  label_short: {
    "Gold": "Gold",
    "Blue Portrait": "Blue Portrait",
    "Black Pearl": "Black Pearl",
    "Franchise Future": "Franchise Future",
    "Franchise Future Signature": "FF Signature",
    "Franchise Greats": "Franchise Greats",
    "Franchise Greats Signature": "FG Signature",
    "Franchise Greats Dual Signature": "FG Dual Sig",
    "Superstar Patch": "Superstar Patch",
    "Triple Superstar Patch": "Triple Patch",
    "Superstar Patch Signature Booklet": "Patch Sig Booklet",
    "Career Games": "Career Games",
    "Career Games Signature": "CG Signature",
    "Premiership Glory": "Prem Glory",
    "Premiership Glory Signature": "PG Signature",
    "Premiership Glory Redemption": "PG Redemption",
    "Goalkicking Greats": "GK Greats",
    "Goalkicking Greats Signature": "GKG Signature",
    "Goalkicking Greats Dual Signature": "GKG Dual Sig",
    "1000 Goalkicker Signature": "1000 GK Sig",
    "Club Captains": "Club Captains",
    "Club Captains Redemption": "CC Redemption",
    "Captain Signature": "Captain Sig",
    "Evolution": "Evolution",
    "Evolution Signature": "Evo Signature",
    "Prem Player Coach Signature": "PPC Signature",
    "Premiership Brownlow Double Signature": "PB Dual Sig",
    "Longest Serving Captains Signature": "LSC Signature",
  }
});

var CARDS_SUPREMACY_2024 = [
  ['1','Jordan Dawson','Gold','Adelaide Crows'],
  ['2','Darcy Fogarty','Gold','Adelaide Crows'],
  ['3','Ben Keays','Gold','Adelaide Crows'],
  ['4','Rory Laird','Gold','Adelaide Crows'],
  ['5','Reilly O\'Brien','Gold','Adelaide Crows'],
  ['6','Josh Rachele','Gold','Adelaide Crows'],
  ['7','Izak Rankine','Gold','Adelaide Crows'],
  ['8','Jake Soligo','Gold','Adelaide Crows'],
  ['9','Taylor Walker','Gold','Adelaide Crows'],
  ['10','Harris Andrews','Gold','Brisbane Lions'],
  ['11','Will Ashcroft','Gold','Brisbane Lions'],
  ['12','Charlie Cameron','Gold','Brisbane Lions'],
  ['13','Joe Daniher','Gold','Brisbane Lions'],
  ['14','Josh Dunkley','Gold','Brisbane Lions'],
  ['15','Eric Hipwood','Gold','Brisbane Lions'],
  ['16','Hugh McCluggage','Gold','Brisbane Lions'],
  ['17','Lachie Neale','Gold','Brisbane Lions'],
  ['18','Cameron Rayner','Gold','Brisbane Lions'],
  ['19','Adam Cerra','Gold','Carlton'],
  ['20','Patrick Cripps','Gold','Carlton'],
  ['21','Charlie Curnow','Gold','Carlton'],
  ['22','Sam Docherty','Gold','Carlton'],
  ['23','Oliver Hollands','Gold','Carlton'],
  ['24','Harry McKay','Gold','Carlton'],
  ['25','Adam Saad','Gold','Carlton'],
  ['26','Samuel Walsh','Gold','Carlton'],
  ['27','Jacob Weitering','Gold','Carlton'],
  ['28','Jack Crisp','Gold','Collingwood'],
  ['29','Josh Daicos','Gold','Collingwood'],
  ['30','Nick Daicos','Gold','Collingwood'],
  ['31','Jordan De Goey','Gold','Collingwood'],
  ['32','Ian Hill','Gold','Collingwood'],
  ['33','Brayden Maynard','Gold','Collingwood'],
  ['34','Darcy Moore','Gold','Collingwood'],
  ['35','Scott Pendlebury','Gold','Collingwood'],
  ['36','Steele Sidebottom','Gold','Collingwood'],
  ['37','Sam Draper','Gold','Essendon'],
  ['38','Kyle Langford','Gold','Essendon'],
  ['39','Nic Martin','Gold','Essendon'],
  ['40','Andrew McGrath','Gold','Essendon'],
  ['41','Zach Merrett','Gold','Essendon'],
  ['42','Darcy Parish','Gold','Essendon'],
  ['43','Archie Perkins','Gold','Essendon'],
  ['44','Mason Redman','Gold','Essendon'],
  ['45','Jake Stringer','Gold','Essendon'],
  ['46','Jye Amiss','Gold','Fremantle'],
  ['47','Andrew Brayshaw','Gold','Fremantle'],
  ['48','Sean Darcy','Gold','Fremantle'],
  ['49','Nathan Fyfe','Gold','Fremantle'],
  ['50','Luke Jackson','Gold','Fremantle'],
  ['51','Jaeger O\'Meara','Gold','Fremantle'],
  ['52','Alex Pearce','Gold','Fremantle'],
  ['53','Caleb Serong','Gold','Fremantle'],
  ['54','Michael Walters','Gold','Fremantle'],
  ['55','Mark Blicavs','Gold','Geelong Cats'],
  ['56','Jeremy Cameron','Gold','Geelong Cats'],
  ['57','Patrick Dangerfield','Gold','Geelong Cats'],
  ['58','Sam De Koning','Gold','Geelong Cats'],
  ['59','Mitch Duncan','Gold','Geelong Cats'],
  ['60','Cameron Guthrie','Gold','Geelong Cats'],
  ['61','Tom Hawkins','Gold','Geelong Cats'],
  ['62','Max Holmes','Gold','Geelong Cats'],
  ['63','Tom Stewart','Gold','Geelong Cats'],
  ['64','Stephen Coniglio','Gold','GWS GIANTS'],
  ['65','Tom Green','Gold','GWS GIANTS'],
  ['66','Toby Greene','Gold','GWS GIANTS'],
  ['67','Nick Haynes','Gold','GWS GIANTS'],
  ['68','Harrison Himmelberg','Gold','GWS GIANTS'],
  ['69','Josh Kelly','Gold','GWS GIANTS'],
  ['70','Sam Taylor','Gold','GWS GIANTS'],
  ['71','Callan Ward','Gold','GWS GIANTS'],
  ['72','Lachie Whitfield','Gold','GWS GIANTS'],
  ['73','Noah Anderson','Gold','Gold Coast SUNS'],
  ['74','Sam Collins','Gold','Gold Coast SUNS'],
  ['75','Bailey Humphrey','Gold','Gold Coast SUNS'],
  ['76','Ben King','Gold','Gold Coast SUNS'],
  ['77','Jack Lukosius','Gold','Gold Coast SUNS'],
  ['78','Touk Miller','Gold','Gold Coast SUNS'],
  ['79','Matt Rowell','Gold','Gold Coast SUNS'],
  ['80','Jed Walter','Gold','Gold Coast SUNS'],
  ['81','Jarrod Witts','Gold','Gold Coast SUNS'],
  ['82','Karl Amon','Gold','Hawthorn'],
  ['83','Luke Breust','Gold','Hawthorn'],
  ['84','Will Day','Gold','Hawthorn'],
  ['85','Mitchell Lewis','Gold','Hawthorn'],
  ['86','Cameron MacKenzie','Gold','Hawthorn'],
  ['87','Dylan Moore','Gold','Hawthorn'],
  ['88','Jai Newcombe','Gold','Hawthorn'],
  ['89','James Sicily','Gold','Hawthorn'],
  ['90','James Worpel','Gold','Hawthorn'],
  ['91','Bayley Fritsch','Gold','Melbourne'],
  ['92','Max Gawn','Gold','Melbourne'],
  ['93','Jake Lever','Gold','Melbourne'],
  ['94','Steven May','Gold','Melbourne'],
  ['95','Clayton Oliver','Gold','Melbourne'],
  ['96','Christian Petracca','Gold','Melbourne'],
  ['97','Kysaiah Pickett','Gold','Melbourne'],
  ['98','Jacob Van Rooyen','Gold','Melbourne'],
  ['99','Jack Viney','Gold','Melbourne'],
  ['100','Luke Davies-Uniacke','Gold','North Melbourne'],
  ['101','Nick Larkey','Gold','North Melbourne'],
  ['102','Luke McDonald','Gold','North Melbourne'],
  ['103','Colby McKercher','Gold','North Melbourne'],
  ['104','Tom Powell','Gold','North Melbourne'],
  ['105','Harry Sheezel','Gold','North Melbourne'],
  ['106','Jy Simpkin','Gold','North Melbourne'],
  ['107','George Wardlaw','Gold','North Melbourne'],
  ['108','Cameron Zurhaar','Gold','North Melbourne'],
  ['109','Travis Boak','Gold','Port Adelaide'],
  ['110','Zak Butters','Gold','Port Adelaide'],
  ['111','Darcy Byrne-Jones','Gold','Port Adelaide'],
  ['112','Charlie Dixon','Gold','Port Adelaide'],
  ['113','Jeremy Finlayson','Gold','Port Adelaide'],
  ['114','Jason Horne-Francis','Gold','Port Adelaide'],
  ['115','Dan Houston','Gold','Port Adelaide'],
  ['116','Connor Rozee','Gold','Port Adelaide'],
  ['117','Oliver Wines','Gold','Port Adelaide'],
  ['118','Liam Baker','Gold','Richmond'],
  ['119','Shai Bolton','Gold','Richmond'],
  ['120','Tom.J Lynch','Gold','Richmond'],
  ['121','Dustin Martin','Gold','Richmond'],
  ['122','Toby Nankervis','Gold','Richmond'],
  ['123','Dion Prestia','Gold','Richmond'],
  ['124','Daniel Rioli','Gold','Richmond'],
  ['125','Tim Taranto','Gold','Richmond'],
  ['126','Nick Vlastuin','Gold','Richmond'],
  ['127','Jack Higgins','Gold','St Kilda'],
  ['128','Max (VM) King','Gold','St Kilda'],
  ['129','Rowan Marshall','Gold','St Kilda'],
  ['130','Mitch Owens','Gold','St Kilda'],
  ['131','Mattaes Phillipou','Gold','St Kilda'],
  ['132','Jack Sinclair','Gold','St Kilda'],
  ['133','Jack Steele','Gold','St Kilda'],
  ['134','Nasiah Wanganeen-Milera','Gold','St Kilda'],
  ['135','Darcy Wilson','Gold','St Kilda'],
  ['136','Nicholas Blakey','Gold','Sydney Swans'],
  ['137','Oliver Florent','Gold','Sydney Swans'],
  ['138','Errol Gulden','Gold','Sydney Swans'],
  ['139','Isaac Heeney','Gold','Sydney Swans'],
  ['140','Logan McDonald','Gold','Sydney Swans'],
  ['141','Callum Mills','Gold','Sydney Swans'],
  ['142','Tom Papley','Gold','Sydney Swans'],
  ['143','Luke Parker','Gold','Sydney Swans'],
  ['144','Chad Warner','Gold','Sydney Swans'],
  ['145','Oscar Allen','Gold','West Coast Eagles'],
  ['146','Tom Barrass','Gold','West Coast Eagles'],
  ['147','Jack Darling','Gold','West Coast Eagles'],
  ['148','Reuben Ginbey','Gold','West Coast Eagles'],
  ['149','Elijah Hewett','Gold','West Coast Eagles'],
  ['150','Tim Kelly','Gold','West Coast Eagles'],
  ['151','Jeremy McGovern','Gold','West Coast Eagles'],
  ['152','Harley Reid','Gold','West Coast Eagles'],
  ['153','Dominic Sheed','Gold','West Coast Eagles'],
  ['154','Marcus Bontempelli','Gold','Western Bulldogs'],
  ['155','Bailey Dale','Gold','Western Bulldogs'],
  ['156','Timothy English','Gold','Western Bulldogs'],
  ['157','Tom Liberatore','Gold','Western Bulldogs'],
  ['158','Jackson Macrae','Gold','Western Bulldogs'],
  ['159','Aaron Naughton','Gold','Western Bulldogs'],
  ['160','Bailey Smith','Gold','Western Bulldogs'],
  ['161','Jamarra Ugle-Hagan','Gold','Western Bulldogs'],
  ['162','Cody Weightman','Gold','Western Bulldogs'],
  ['1','Jordan Dawson','Blue Portrait','Adelaide Crows'],
  ['2','Darcy Fogarty','Blue Portrait','Adelaide Crows'],
  ['3','Ben Keays','Blue Portrait','Adelaide Crows'],
  ['4','Rory Laird','Blue Portrait','Adelaide Crows'],
  ['5','Reilly O\'Brien','Blue Portrait','Adelaide Crows'],
  ['6','Josh Rachele','Blue Portrait','Adelaide Crows'],
  ['7','Izak Rankine','Blue Portrait','Adelaide Crows'],
  ['8','Jake Soligo','Blue Portrait','Adelaide Crows'],
  ['9','Taylor Walker','Blue Portrait','Adelaide Crows'],
  ['10','Harris Andrews','Blue Portrait','Brisbane Lions'],
  ['11','Will Ashcroft','Blue Portrait','Brisbane Lions'],
  ['12','Charlie Cameron','Blue Portrait','Brisbane Lions'],
  ['13','Joe Daniher','Blue Portrait','Brisbane Lions'],
  ['14','Josh Dunkley','Blue Portrait','Brisbane Lions'],
  ['15','Eric Hipwood','Blue Portrait','Brisbane Lions'],
  ['16','Hugh McCluggage','Blue Portrait','Brisbane Lions'],
  ['17','Lachie Neale','Blue Portrait','Brisbane Lions'],
  ['18','Cameron Rayner','Blue Portrait','Brisbane Lions'],
  ['19','Adam Cerra','Blue Portrait','Carlton'],
  ['20','Patrick Cripps','Blue Portrait','Carlton'],
  ['21','Charlie Curnow','Blue Portrait','Carlton'],
  ['22','Sam Docherty','Blue Portrait','Carlton'],
  ['23','Oliver Hollands','Blue Portrait','Carlton'],
  ['24','Harry McKay','Blue Portrait','Carlton'],
  ['25','Adam Saad','Blue Portrait','Carlton'],
  ['26','Samuel Walsh','Blue Portrait','Carlton'],
  ['27','Jacob Weitering','Blue Portrait','Carlton'],
  ['28','Jack Crisp','Blue Portrait','Collingwood'],
  ['29','Josh Daicos','Blue Portrait','Collingwood'],
  ['30','Nick Daicos','Blue Portrait','Collingwood'],
  ['31','Jordan De Goey','Blue Portrait','Collingwood'],
  ['32','Ian Hill','Blue Portrait','Collingwood'],
  ['33','Brayden Maynard','Blue Portrait','Collingwood'],
  ['34','Darcy Moore','Blue Portrait','Collingwood'],
  ['35','Scott Pendlebury','Blue Portrait','Collingwood'],
  ['36','Steele Sidebottom','Blue Portrait','Collingwood'],
  ['37','Sam Draper','Blue Portrait','Essendon'],
  ['38','Kyle Langford','Blue Portrait','Essendon'],
  ['39','Nic Martin','Blue Portrait','Essendon'],
  ['40','Andrew McGrath','Blue Portrait','Essendon'],
  ['41','Zach Merrett','Blue Portrait','Essendon'],
  ['42','Darcy Parish','Blue Portrait','Essendon'],
  ['43','Archie Perkins','Blue Portrait','Essendon'],
  ['44','Mason Redman','Blue Portrait','Essendon'],
  ['45','Jake Stringer','Blue Portrait','Essendon'],
  ['46','Jye Amiss','Blue Portrait','Fremantle'],
  ['47','Andrew Brayshaw','Blue Portrait','Fremantle'],
  ['48','Sean Darcy','Blue Portrait','Fremantle'],
  ['49','Nathan Fyfe','Blue Portrait','Fremantle'],
  ['50','Luke Jackson','Blue Portrait','Fremantle'],
  ['51','Jaeger O\'Meara','Blue Portrait','Fremantle'],
  ['52','Alex Pearce','Blue Portrait','Fremantle'],
  ['53','Caleb Serong','Blue Portrait','Fremantle'],
  ['54','Michael Walters','Blue Portrait','Fremantle'],
  ['55','Mark Blicavs','Blue Portrait','Geelong Cats'],
  ['56','Jeremy Cameron','Blue Portrait','Geelong Cats'],
  ['57','Patrick Dangerfield','Blue Portrait','Geelong Cats'],
  ['58','Sam De Koning','Blue Portrait','Geelong Cats'],
  ['59','Mitch Duncan','Blue Portrait','Geelong Cats'],
  ['60','Cameron Guthrie','Blue Portrait','Geelong Cats'],
  ['61','Tom Hawkins','Blue Portrait','Geelong Cats'],
  ['62','Max Holmes','Blue Portrait','Geelong Cats'],
  ['63','Tom Stewart','Blue Portrait','Geelong Cats'],
  ['64','Stephen Coniglio','Blue Portrait','GWS GIANTS'],
  ['65','Tom Green','Blue Portrait','GWS GIANTS'],
  ['66','Toby Greene','Blue Portrait','GWS GIANTS'],
  ['67','Nick Haynes','Blue Portrait','GWS GIANTS'],
  ['68','Harrison Himmelberg','Blue Portrait','GWS GIANTS'],
  ['69','Josh Kelly','Blue Portrait','GWS GIANTS'],
  ['70','Sam Taylor','Blue Portrait','GWS GIANTS'],
  ['71','Callan Ward','Blue Portrait','GWS GIANTS'],
  ['72','Lachie Whitfield','Blue Portrait','GWS GIANTS'],
  ['73','Noah Anderson','Blue Portrait','Gold Coast SUNS'],
  ['74','Sam Collins','Blue Portrait','Gold Coast SUNS'],
  ['75','Bailey Humphrey','Blue Portrait','Gold Coast SUNS'],
  ['76','Ben King','Blue Portrait','Gold Coast SUNS'],
  ['77','Jack Lukosius','Blue Portrait','Gold Coast SUNS'],
  ['78','Touk Miller','Blue Portrait','Gold Coast SUNS'],
  ['79','Matt Rowell','Blue Portrait','Gold Coast SUNS'],
  ['80','Jed Walter','Blue Portrait','Gold Coast SUNS'],
  ['81','Jarrod Witts','Blue Portrait','Gold Coast SUNS'],
  ['82','Karl Amon','Blue Portrait','Hawthorn'],
  ['83','Luke Breust','Blue Portrait','Hawthorn'],
  ['84','Will Day','Blue Portrait','Hawthorn'],
  ['85','Mitchell Lewis','Blue Portrait','Hawthorn'],
  ['86','Cameron MacKenzie','Blue Portrait','Hawthorn'],
  ['87','Dylan Moore','Blue Portrait','Hawthorn'],
  ['88','Jai Newcombe','Blue Portrait','Hawthorn'],
  ['89','James Sicily','Blue Portrait','Hawthorn'],
  ['90','James Worpel','Blue Portrait','Hawthorn'],
  ['91','Bayley Fritsch','Blue Portrait','Melbourne'],
  ['92','Max Gawn','Blue Portrait','Melbourne'],
  ['93','Jake Lever','Blue Portrait','Melbourne'],
  ['94','Steven May','Blue Portrait','Melbourne'],
  ['95','Clayton Oliver','Blue Portrait','Melbourne'],
  ['96','Christian Petracca','Blue Portrait','Melbourne'],
  ['97','Kysaiah Pickett','Blue Portrait','Melbourne'],
  ['98','Jacob Van Rooyen','Blue Portrait','Melbourne'],
  ['99','Jack Viney','Blue Portrait','Melbourne'],
  ['100','Luke Davies-Uniacke','Blue Portrait','North Melbourne'],
  ['101','Nick Larkey','Blue Portrait','North Melbourne'],
  ['102','Luke McDonald','Blue Portrait','North Melbourne'],
  ['103','Colby McKercher','Blue Portrait','North Melbourne'],
  ['104','Tom Powell','Blue Portrait','North Melbourne'],
  ['105','Harry Sheezel','Blue Portrait','North Melbourne'],
  ['106','Jy Simpkin','Blue Portrait','North Melbourne'],
  ['107','George Wardlaw','Blue Portrait','North Melbourne'],
  ['108','Cameron Zurhaar','Blue Portrait','North Melbourne'],
  ['109','Travis Boak','Blue Portrait','Port Adelaide'],
  ['110','Zak Butters','Blue Portrait','Port Adelaide'],
  ['111','Darcy Byrne-Jones','Blue Portrait','Port Adelaide'],
  ['112','Charlie Dixon','Blue Portrait','Port Adelaide'],
  ['113','Jeremy Finlayson','Blue Portrait','Port Adelaide'],
  ['114','Jason Horne-Francis','Blue Portrait','Port Adelaide'],
  ['115','Dan Houston','Blue Portrait','Port Adelaide'],
  ['116','Connor Rozee','Blue Portrait','Port Adelaide'],
  ['117','Oliver Wines','Blue Portrait','Port Adelaide'],
  ['118','Liam Baker','Blue Portrait','Richmond'],
  ['119','Shai Bolton','Blue Portrait','Richmond'],
  ['120','Tom.J Lynch','Blue Portrait','Richmond'],
  ['121','Dustin Martin','Blue Portrait','Richmond'],
  ['122','Toby Nankervis','Blue Portrait','Richmond'],
  ['123','Dion Prestia','Blue Portrait','Richmond'],
  ['124','Daniel Rioli','Blue Portrait','Richmond'],
  ['125','Tim Taranto','Blue Portrait','Richmond'],
  ['126','Nick Vlastuin','Blue Portrait','Richmond'],
  ['127','Jack Higgins','Blue Portrait','St Kilda'],
  ['128','Max (VM) King','Blue Portrait','St Kilda'],
  ['129','Rowan Marshall','Blue Portrait','St Kilda'],
  ['130','Mitch Owens','Blue Portrait','St Kilda'],
  ['131','Mattaes Phillipou','Blue Portrait','St Kilda'],
  ['132','Jack Sinclair','Blue Portrait','St Kilda'],
  ['133','Jack Steele','Blue Portrait','St Kilda'],
  ['134','Nasiah Wanganeen-Milera','Blue Portrait','St Kilda'],
  ['135','Darcy Wilson','Blue Portrait','St Kilda'],
  ['136','Nicholas Blakey','Blue Portrait','Sydney Swans'],
  ['137','Oliver Florent','Blue Portrait','Sydney Swans'],
  ['138','Errol Gulden','Blue Portrait','Sydney Swans'],
  ['139','Isaac Heeney','Blue Portrait','Sydney Swans'],
  ['140','Logan McDonald','Blue Portrait','Sydney Swans'],
  ['141','Callum Mills','Blue Portrait','Sydney Swans'],
  ['142','Tom Papley','Blue Portrait','Sydney Swans'],
  ['143','Luke Parker','Blue Portrait','Sydney Swans'],
  ['144','Chad Warner','Blue Portrait','Sydney Swans'],
  ['145','Oscar Allen','Blue Portrait','West Coast Eagles'],
  ['146','Tom Barrass','Blue Portrait','West Coast Eagles'],
  ['147','Jack Darling','Blue Portrait','West Coast Eagles'],
  ['148','Reuben Ginbey','Blue Portrait','West Coast Eagles'],
  ['149','Elijah Hewett','Blue Portrait','West Coast Eagles'],
  ['150','Tim Kelly','Blue Portrait','West Coast Eagles'],
  ['151','Jeremy McGovern','Blue Portrait','West Coast Eagles'],
  ['152','Harley Reid','Blue Portrait','West Coast Eagles'],
  ['153','Dominic Sheed','Blue Portrait','West Coast Eagles'],
  ['154','Marcus Bontempelli','Blue Portrait','Western Bulldogs'],
  ['155','Bailey Dale','Blue Portrait','Western Bulldogs'],
  ['156','Timothy English','Blue Portrait','Western Bulldogs'],
  ['157','Tom Liberatore','Blue Portrait','Western Bulldogs'],
  ['158','Jackson Macrae','Blue Portrait','Western Bulldogs'],
  ['159','Aaron Naughton','Blue Portrait','Western Bulldogs'],
  ['160','Bailey Smith','Blue Portrait','Western Bulldogs'],
  ['161','Jamarra Ugle-Hagan','Blue Portrait','Western Bulldogs'],
  ['162','Cody Weightman','Blue Portrait','Western Bulldogs'],
  ['1','Jordan Dawson','Black Pearl','Adelaide Crows'],
  ['2','Darcy Fogarty','Black Pearl','Adelaide Crows'],
  ['3','Ben Keays','Black Pearl','Adelaide Crows'],
  ['4','Rory Laird','Black Pearl','Adelaide Crows'],
  ['5','Reilly O\'Brien','Black Pearl','Adelaide Crows'],
  ['6','Josh Rachele','Black Pearl','Adelaide Crows'],
  ['7','Izak Rankine','Black Pearl','Adelaide Crows'],
  ['8','Jake Soligo','Black Pearl','Adelaide Crows'],
  ['9','Taylor Walker','Black Pearl','Adelaide Crows'],
  ['10','Harris Andrews','Black Pearl','Brisbane Lions'],
  ['11','Will Ashcroft','Black Pearl','Brisbane Lions'],
  ['12','Charlie Cameron','Black Pearl','Brisbane Lions'],
  ['13','Joe Daniher','Black Pearl','Brisbane Lions'],
  ['14','Josh Dunkley','Black Pearl','Brisbane Lions'],
  ['15','Eric Hipwood','Black Pearl','Brisbane Lions'],
  ['16','Hugh McCluggage','Black Pearl','Brisbane Lions'],
  ['17','Lachie Neale','Black Pearl','Brisbane Lions'],
  ['18','Cameron Rayner','Black Pearl','Brisbane Lions'],
  ['19','Adam Cerra','Black Pearl','Carlton'],
  ['20','Patrick Cripps','Black Pearl','Carlton'],
  ['21','Charlie Curnow','Black Pearl','Carlton'],
  ['22','Sam Docherty','Black Pearl','Carlton'],
  ['23','Oliver Hollands','Black Pearl','Carlton'],
  ['24','Harry McKay','Black Pearl','Carlton'],
  ['25','Adam Saad','Black Pearl','Carlton'],
  ['26','Samuel Walsh','Black Pearl','Carlton'],
  ['27','Jacob Weitering','Black Pearl','Carlton'],
  ['28','Jack Crisp','Black Pearl','Collingwood'],
  ['29','Josh Daicos','Black Pearl','Collingwood'],
  ['30','Nick Daicos','Black Pearl','Collingwood'],
  ['31','Jordan De Goey','Black Pearl','Collingwood'],
  ['32','Ian Hill','Black Pearl','Collingwood'],
  ['33','Brayden Maynard','Black Pearl','Collingwood'],
  ['34','Darcy Moore','Black Pearl','Collingwood'],
  ['35','Scott Pendlebury','Black Pearl','Collingwood'],
  ['36','Steele Sidebottom','Black Pearl','Collingwood'],
  ['37','Sam Draper','Black Pearl','Essendon'],
  ['38','Kyle Langford','Black Pearl','Essendon'],
  ['39','Nic Martin','Black Pearl','Essendon'],
  ['40','Andrew McGrath','Black Pearl','Essendon'],
  ['41','Zach Merrett','Black Pearl','Essendon'],
  ['42','Darcy Parish','Black Pearl','Essendon'],
  ['43','Archie Perkins','Black Pearl','Essendon'],
  ['44','Mason Redman','Black Pearl','Essendon'],
  ['45','Jake Stringer','Black Pearl','Essendon'],
  ['46','Jye Amiss','Black Pearl','Fremantle'],
  ['47','Andrew Brayshaw','Black Pearl','Fremantle'],
  ['48','Sean Darcy','Black Pearl','Fremantle'],
  ['49','Nathan Fyfe','Black Pearl','Fremantle'],
  ['50','Luke Jackson','Black Pearl','Fremantle'],
  ['51','Jaeger O\'Meara','Black Pearl','Fremantle'],
  ['52','Alex Pearce','Black Pearl','Fremantle'],
  ['53','Caleb Serong','Black Pearl','Fremantle'],
  ['54','Michael Walters','Black Pearl','Fremantle'],
  ['55','Mark Blicavs','Black Pearl','Geelong Cats'],
  ['56','Jeremy Cameron','Black Pearl','Geelong Cats'],
  ['57','Patrick Dangerfield','Black Pearl','Geelong Cats'],
  ['58','Sam De Koning','Black Pearl','Geelong Cats'],
  ['59','Mitch Duncan','Black Pearl','Geelong Cats'],
  ['60','Cameron Guthrie','Black Pearl','Geelong Cats'],
  ['61','Tom Hawkins','Black Pearl','Geelong Cats'],
  ['62','Max Holmes','Black Pearl','Geelong Cats'],
  ['63','Tom Stewart','Black Pearl','Geelong Cats'],
  ['64','Stephen Coniglio','Black Pearl','GWS GIANTS'],
  ['65','Tom Green','Black Pearl','GWS GIANTS'],
  ['66','Toby Greene','Black Pearl','GWS GIANTS'],
  ['67','Nick Haynes','Black Pearl','GWS GIANTS'],
  ['68','Harrison Himmelberg','Black Pearl','GWS GIANTS'],
  ['69','Josh Kelly','Black Pearl','GWS GIANTS'],
  ['70','Sam Taylor','Black Pearl','GWS GIANTS'],
  ['71','Callan Ward','Black Pearl','GWS GIANTS'],
  ['72','Lachie Whitfield','Black Pearl','GWS GIANTS'],
  ['73','Noah Anderson','Black Pearl','Gold Coast SUNS'],
  ['74','Sam Collins','Black Pearl','Gold Coast SUNS'],
  ['75','Bailey Humphrey','Black Pearl','Gold Coast SUNS'],
  ['76','Ben King','Black Pearl','Gold Coast SUNS'],
  ['77','Jack Lukosius','Black Pearl','Gold Coast SUNS'],
  ['78','Touk Miller','Black Pearl','Gold Coast SUNS'],
  ['79','Matt Rowell','Black Pearl','Gold Coast SUNS'],
  ['80','Jed Walter','Black Pearl','Gold Coast SUNS'],
  ['81','Jarrod Witts','Black Pearl','Gold Coast SUNS'],
  ['82','Karl Amon','Black Pearl','Hawthorn'],
  ['83','Luke Breust','Black Pearl','Hawthorn'],
  ['84','Will Day','Black Pearl','Hawthorn'],
  ['85','Mitchell Lewis','Black Pearl','Hawthorn'],
  ['86','Cameron MacKenzie','Black Pearl','Hawthorn'],
  ['87','Dylan Moore','Black Pearl','Hawthorn'],
  ['88','Jai Newcombe','Black Pearl','Hawthorn'],
  ['89','James Sicily','Black Pearl','Hawthorn'],
  ['90','James Worpel','Black Pearl','Hawthorn'],
  ['91','Bayley Fritsch','Black Pearl','Melbourne'],
  ['92','Max Gawn','Black Pearl','Melbourne'],
  ['93','Jake Lever','Black Pearl','Melbourne'],
  ['94','Steven May','Black Pearl','Melbourne'],
  ['95','Clayton Oliver','Black Pearl','Melbourne'],
  ['96','Christian Petracca','Black Pearl','Melbourne'],
  ['97','Kysaiah Pickett','Black Pearl','Melbourne'],
  ['98','Jacob Van Rooyen','Black Pearl','Melbourne'],
  ['99','Jack Viney','Black Pearl','Melbourne'],
  ['100','Luke Davies-Uniacke','Black Pearl','North Melbourne'],
  ['101','Nick Larkey','Black Pearl','North Melbourne'],
  ['102','Luke McDonald','Black Pearl','North Melbourne'],
  ['103','Colby McKercher','Black Pearl','North Melbourne'],
  ['104','Tom Powell','Black Pearl','North Melbourne'],
  ['105','Harry Sheezel','Black Pearl','North Melbourne'],
  ['106','Jy Simpkin','Black Pearl','North Melbourne'],
  ['107','George Wardlaw','Black Pearl','North Melbourne'],
  ['108','Cameron Zurhaar','Black Pearl','North Melbourne'],
  ['109','Travis Boak','Black Pearl','Port Adelaide'],
  ['110','Zak Butters','Black Pearl','Port Adelaide'],
  ['111','Darcy Byrne-Jones','Black Pearl','Port Adelaide'],
  ['112','Charlie Dixon','Black Pearl','Port Adelaide'],
  ['113','Jeremy Finlayson','Black Pearl','Port Adelaide'],
  ['114','Jason Horne-Francis','Black Pearl','Port Adelaide'],
  ['115','Dan Houston','Black Pearl','Port Adelaide'],
  ['116','Connor Rozee','Black Pearl','Port Adelaide'],
  ['117','Oliver Wines','Black Pearl','Port Adelaide'],
  ['118','Liam Baker','Black Pearl','Richmond'],
  ['119','Shai Bolton','Black Pearl','Richmond'],
  ['120','Tom.J Lynch','Black Pearl','Richmond'],
  ['121','Dustin Martin','Black Pearl','Richmond'],
  ['122','Toby Nankervis','Black Pearl','Richmond'],
  ['123','Dion Prestia','Black Pearl','Richmond'],
  ['124','Daniel Rioli','Black Pearl','Richmond'],
  ['125','Tim Taranto','Black Pearl','Richmond'],
  ['126','Nick Vlastuin','Black Pearl','Richmond'],
  ['127','Jack Higgins','Black Pearl','St Kilda'],
  ['128','Max (VM) King','Black Pearl','St Kilda'],
  ['129','Rowan Marshall','Black Pearl','St Kilda'],
  ['130','Mitch Owens','Black Pearl','St Kilda'],
  ['131','Mattaes Phillipou','Black Pearl','St Kilda'],
  ['132','Jack Sinclair','Black Pearl','St Kilda'],
  ['133','Jack Steele','Black Pearl','St Kilda'],
  ['134','Nasiah Wanganeen-Milera','Black Pearl','St Kilda'],
  ['135','Darcy Wilson','Black Pearl','St Kilda'],
  ['136','Nicholas Blakey','Black Pearl','Sydney Swans'],
  ['137','Oliver Florent','Black Pearl','Sydney Swans'],
  ['138','Errol Gulden','Black Pearl','Sydney Swans'],
  ['139','Isaac Heeney','Black Pearl','Sydney Swans'],
  ['140','Logan McDonald','Black Pearl','Sydney Swans'],
  ['141','Callum Mills','Black Pearl','Sydney Swans'],
  ['142','Tom Papley','Black Pearl','Sydney Swans'],
  ['143','Luke Parker','Black Pearl','Sydney Swans'],
  ['144','Chad Warner','Black Pearl','Sydney Swans'],
  ['145','Oscar Allen','Black Pearl','West Coast Eagles'],
  ['146','Tom Barrass','Black Pearl','West Coast Eagles'],
  ['147','Jack Darling','Black Pearl','West Coast Eagles'],
  ['148','Reuben Ginbey','Black Pearl','West Coast Eagles'],
  ['149','Elijah Hewett','Black Pearl','West Coast Eagles'],
  ['150','Tim Kelly','Black Pearl','West Coast Eagles'],
  ['151','Jeremy McGovern','Black Pearl','West Coast Eagles'],
  ['152','Harley Reid','Black Pearl','West Coast Eagles'],
  ['153','Dominic Sheed','Black Pearl','West Coast Eagles'],
  ['154','Marcus Bontempelli','Black Pearl','Western Bulldogs'],
  ['155','Bailey Dale','Black Pearl','Western Bulldogs'],
  ['156','Timothy English','Black Pearl','Western Bulldogs'],
  ['157','Tom Liberatore','Black Pearl','Western Bulldogs'],
  ['158','Jackson Macrae','Black Pearl','Western Bulldogs'],
  ['159','Aaron Naughton','Black Pearl','Western Bulldogs'],
  ['160','Bailey Smith','Black Pearl','Western Bulldogs'],
  ['161','Jamarra Ugle-Hagan','Black Pearl','Western Bulldogs'],
  ['162','Cody Weightman','Black Pearl','Western Bulldogs'],
  ['FF1','Josh Rachele','Franchise Future','Adelaide Crows'],
  ['FF2','Riley Thilthorpe','Franchise Future','Adelaide Crows'],
  ['FF3','Zac Bailey','Franchise Future','Brisbane Lions'],
  ['FF4','Keidean Coleman','Franchise Future','Brisbane Lions'],
  ['FF5','Oliver Hollands','Franchise Future','Carlton'],
  ['FF6','Tom De Koning','Franchise Future','Carlton'],
  ['FF7','Nick Daicos','Franchise Future','Collingwood'],
  ['FF8','Isaac Quaynor','Franchise Future','Collingwood'],
  ['FF9','Ben Hobbs','Franchise Future','Essendon'],
  ['FF10','Archie Perkins','Franchise Future','Essendon'],
  ['FF11','Jye Amiss','Franchise Future','Fremantle'],
  ['FF12','Caleb Serong','Franchise Future','Fremantle'],
  ['FF13','Sam De Koning','Franchise Future','Geelong Cats'],
  ['FF14','Max Holmes','Franchise Future','Geelong Cats'],
  ['FF15','Tom Green','Franchise Future','GWS GIANTS'],
  ['FF16','Sam Taylor','Franchise Future','GWS GIANTS'],
  ['FF17','Noah Anderson','Franchise Future','Gold Coast SUNS'],
  ['FF18','Jack Lukosius','Franchise Future','Gold Coast SUNS'],
  ['FF19','Mitchell Lewis','Franchise Future','Hawthorn'],
  ['FF20','Jai Newcombe','Franchise Future','Hawthorn'],
  ['FF21','Jake Bowey','Franchise Future','Melbourne'],
  ['FF22','Jacob Van Rooyen','Franchise Future','Melbourne'],
  ['FF23','Harry Sheezel','Franchise Future','North Melbourne'],
  ['FF24','George Wardlaw','Franchise Future','North Melbourne'],
  ['FF25','Mitchell Georgiadis','Franchise Future','Port Adelaide'],
  ['FF26','Jason Horne-Francis','Franchise Future','Port Adelaide'],
  ['FF27','Shai Bolton','Franchise Future','Richmond'],
  ['FF28','Josh Gibcus','Franchise Future','Richmond'],
  ['FF29','Nasiah Wanganeen-Milera','Franchise Future','St Kilda'],
  ['FF30','Mitch Owens','Franchise Future','St Kilda'],
  ['FF31','Errol Gulden','Franchise Future','Sydney Swans'],
  ['FF32','Chad Warner','Franchise Future','Sydney Swans'],
  ['FF33','Elijah Hewett','Franchise Future','West Coast Eagles'],
  ['FF34','Reuben Ginbey','Franchise Future','West Coast Eagles'],
  ['FF35','Jamarra Ugle-Hagan','Franchise Future','Western Bulldogs'],
  ['FF36','Cody Weightman','Franchise Future','Western Bulldogs'],
  ['FFS1','Josh Rachele','Franchise Future Signature','Adelaide Crows'],
  ['FFS2','Riley Thilthorpe','Franchise Future Signature','Adelaide Crows'],
  ['FFS3','Zac Bailey','Franchise Future Signature','Brisbane Lions'],
  ['FFS4','Keidean Coleman','Franchise Future Signature','Brisbane Lions'],
  ['FFS5','Oliver Hollands','Franchise Future Signature','Carlton'],
  ['FFS6','Tom De Koning','Franchise Future Signature','Carlton'],
  ['FFS7','Nick Daicos','Franchise Future Signature','Collingwood'],
  ['FFS8','Isaac Quaynor','Franchise Future Signature','Collingwood'],
  ['FFS9','Ben Hobbs','Franchise Future Signature','Essendon'],
  ['FFS10','Archie Perkins','Franchise Future Signature','Essendon'],
  ['FFS11','Jye Amiss','Franchise Future Signature','Fremantle'],
  ['FFS12','Caleb Serong','Franchise Future Signature','Fremantle'],
  ['FFS13','Sam De Koning','Franchise Future Signature','Geelong Cats'],
  ['FFS14','Max Holmes','Franchise Future Signature','Geelong Cats'],
  ['FFS15','Tom Green','Franchise Future Signature','GWS GIANTS'],
  ['FFS16','Sam Taylor','Franchise Future Signature','GWS GIANTS'],
  ['FFS17','Noah Anderson','Franchise Future Signature','Gold Coast SUNS'],
  ['FFS18','Jack Lukosius','Franchise Future Signature','Gold Coast SUNS'],
  ['FFS19','Mitchell Lewis','Franchise Future Signature','Hawthorn'],
  ['FFS20','Jai Newcombe','Franchise Future Signature','Hawthorn'],
  ['FFS21','Jake Bowey','Franchise Future Signature','Melbourne'],
  ['FFS22','Jacob Van Rooyen','Franchise Future Signature','Melbourne'],
  ['FFS23','Harry Sheezel','Franchise Future Signature','North Melbourne'],
  ['FFS24','George Wardlaw','Franchise Future Signature','North Melbourne'],
  ['FFS25','Mitchell Georgiadis','Franchise Future Signature','Port Adelaide'],
  ['FFS26','Jason Horne-Francis','Franchise Future Signature','Port Adelaide'],
  ['FFS27','Shai Bolton','Franchise Future Signature','Richmond'],
  ['FFS28','Josh Gibcus','Franchise Future Signature','Richmond'],
  ['FFS29','Nasiah Wanganeen-Milera','Franchise Future Signature','St Kilda'],
  ['FFS30','Mitch Owens','Franchise Future Signature','St Kilda'],
  ['FFS31','Errol Gulden','Franchise Future Signature','Sydney Swans'],
  ['FFS32','Chad Warner','Franchise Future Signature','Sydney Swans'],
  ['FFS33','Elijah Hewett','Franchise Future Signature','West Coast Eagles'],
  ['FFS34','Reuben Ginbey','Franchise Future Signature','West Coast Eagles'],
  ['FFS35','Jamarra Ugle-Hagan','Franchise Future Signature','Western Bulldogs'],
  ['FFS36','Cody Weightman','Franchise Future Signature','Western Bulldogs'],
  ['FG1','Jordan Dawson','Franchise Greats','Adelaide Crows'],
  ['FG2','Mark Ricciuto','Franchise Greats','Adelaide Crows'],
  ['FG3','Lachie Neale','Franchise Greats','Brisbane Lions'],
  ['FG4','Jonathon Brown','Franchise Greats','Brisbane Lions'],
  ['FG5','Patrick Cripps','Franchise Greats','Carlton'],
  ['FG6','Anthony Koutoufides','Franchise Greats','Carlton'],
  ['FG7','Scott Pendlebury','Franchise Greats','Collingwood'],
  ['FG8','Nathan Buckley','Franchise Greats','Collingwood'],
  ['FG9','Zach Merrett','Franchise Greats','Essendon'],
  ['FG10','James Hird','Franchise Greats','Essendon'],
  ['FG11','Andrew Brayshaw','Franchise Greats','Fremantle'],
  ['FG12','David Mundy','Franchise Greats','Fremantle'],
  ['FG13','Patrick Dangerfield','Franchise Greats','Geelong Cats'],
  ['FG14','Joel Selwood','Franchise Greats','Geelong Cats'],
  ['FG15','Toby Greene','Franchise Greats','GWS GIANTS'],
  ['FG16','Callan Ward','Franchise Greats','GWS GIANTS'],
  ['FG17','Ben King','Franchise Greats','Gold Coast SUNS'],
  ['FG18','Gary (jnr) Ablett','Franchise Greats','Gold Coast SUNS'],
  ['FG19','James Sicily','Franchise Greats','Hawthorn'],
  ['FG20','Dermott Brereton','Franchise Greats','Hawthorn'],
  ['FG21','Christian Petracca','Franchise Greats','Melbourne'],
  ['FG22','Max Gawn','Franchise Greats','Melbourne'],
  ['FG23','Nick Larkey','Franchise Greats','North Melbourne'],
  ['FG24','Glen Archer','Franchise Greats','North Melbourne'],
  ['FG25','Travis Boak','Franchise Greats','Port Adelaide'],
  ['FG26','Gavin Wanganeen','Franchise Greats','Port Adelaide'],
  ['FG27','Trent Cotchin','Franchise Greats','Richmond'],
  ['FG28','Matthew Richardson','Franchise Greats','Richmond'],
  ['FG29','Jack Steele','Franchise Greats','St Kilda'],
  ['FG30','Robert Harvey','Franchise Greats','St Kilda'],
  ['FG31','Luke Parker','Franchise Greats','Sydney Swans'],
  ['FG32','Paul Kelly','Franchise Greats','Sydney Swans'],
  ['FG33','Dominic Sheed','Franchise Greats','West Coast Eagles'],
  ['FG34','Ben Cousins','Franchise Greats','West Coast Eagles'],
  ['FG35','Marcus Bontempelli','Franchise Greats','Western Bulldogs'],
  ['FG36','Robert Murphy','Franchise Greats','Western Bulldogs'],
  ['FGS1','Jordan Dawson','Franchise Greats Signature','Adelaide Crows'],
  ['FGS2','Mark Ricciuto','Franchise Greats Signature','Adelaide Crows'],
  ['FGS3','Lachie Neale','Franchise Greats Signature','Brisbane Lions'],
  ['FGS4','Jonathon Brown','Franchise Greats Signature','Brisbane Lions'],
  ['FGS5','Patrick Cripps','Franchise Greats Signature','Carlton'],
  ['FGS6','Anthony Koutoufides','Franchise Greats Signature','Carlton'],
  ['FGS7','Scott Pendlebury','Franchise Greats Signature','Collingwood'],
  ['FGS8','Nathan Buckley','Franchise Greats Signature','Collingwood'],
  ['FGS9','Zach Merrett','Franchise Greats Signature','Essendon'],
  ['FGS10','James Hird','Franchise Greats Signature','Essendon'],
  ['FGS11','Andrew Brayshaw','Franchise Greats Signature','Fremantle'],
  ['FGS12','David Mundy','Franchise Greats Signature','Fremantle'],
  ['FGS13','Patrick Dangerfield','Franchise Greats Signature','Geelong Cats'],
  ['FGS14','Joel Selwood','Franchise Greats Signature','Geelong Cats'],
  ['FGS15','Toby Greene','Franchise Greats Signature','GWS GIANTS'],
  ['FGS16','Callan Ward','Franchise Greats Signature','GWS GIANTS'],
  ['FGS17','Ben King','Franchise Greats Signature','Gold Coast SUNS'],
  ['FGS18','Gary (jnr) Ablett','Franchise Greats Signature','Gold Coast SUNS'],
  ['FGS19','James Sicily','Franchise Greats Signature','Hawthorn'],
  ['FGS20','Dermott Brereton','Franchise Greats Signature','Hawthorn'],
  ['FGS21','Christian Petracca','Franchise Greats Signature','Melbourne'],
  ['FGS22','Max Gawn','Franchise Greats Signature','Melbourne'],
  ['FGS23','Nick Larkey','Franchise Greats Signature','North Melbourne'],
  ['FGS24','Glen Archer','Franchise Greats Signature','North Melbourne'],
  ['FGS25','Travis Boak','Franchise Greats Signature','Port Adelaide'],
  ['FGS26','Gavin Wanganeen','Franchise Greats Signature','Port Adelaide'],
  ['FGS27','Trent Cotchin','Franchise Greats Signature','Richmond'],
  ['FGS28','Matthew Richardson','Franchise Greats Signature','Richmond'],
  ['FGS29','Jack Steele','Franchise Greats Signature','St Kilda'],
  ['FGS30','Robert Harvey','Franchise Greats Signature','St Kilda'],
  ['FGS31','Luke Parker','Franchise Greats Signature','Sydney Swans'],
  ['FGS32','Paul Kelly','Franchise Greats Signature','Sydney Swans'],
  ['FGS33','Dominic Sheed','Franchise Greats Signature','West Coast Eagles'],
  ['FGS34','Ben Cousins','Franchise Greats Signature','West Coast Eagles'],
  ['FGS35','Marcus Bontempelli','Franchise Greats Signature','Western Bulldogs'],
  ['FGS36','Robert Murphy','Franchise Greats Signature','Western Bulldogs'],
  ['FGDS1','Jordan Dawson - Mark Ricciuto','Franchise Greats Dual Signature','Adelaide Crows'],
  ['FGDS2','Lachie Neale - Jonathon Brown','Franchise Greats Dual Signature','Brisbane Lions'],
  ['FGDS3','Patrick Cripps - Anthony Koutoufides','Franchise Greats Dual Signature','Carlton'],
  ['FGDS4','Scott Pendlebury - Nathan Buckley','Franchise Greats Dual Signature','Collingwood'],
  ['FGDS5','Zach Merrett - James Hird','Franchise Greats Dual Signature','Essendon'],
  ['FGDS6','Andrew Brayshaw - David Mundy','Franchise Greats Dual Signature','Fremantle'],
  ['FGDS7','Patrick Dangerfield - Joel Selwood','Franchise Greats Dual Signature','Geelong Cats'],
  ['FGDS8','Toby Greene - Callan Ward','Franchise Greats Dual Signature','GWS GIANTS'],
  ['FGDS9','Ben King - Gary (jnr) Ablett','Franchise Greats Dual Signature','Gold Coast SUNS'],
  ['FGDS10','James Sicily - Dermott Brereton','Franchise Greats Dual Signature','Hawthorn'],
  ['FGDS11','Christian Petracca - Max Gawn','Franchise Greats Dual Signature','Melbourne'],
  ['FGDS12','Nick Larkey - Glen Archer','Franchise Greats Dual Signature','North Melbourne'],
  ['FGDS13','Travis Boak - Gavin Wanganeen','Franchise Greats Dual Signature','Port Adelaide'],
  ['FGDS14','Trent Cotchin - Matthew Richardson','Franchise Greats Dual Signature','Richmond'],
  ['FGDS15','Jack Steele - Robert Harvey','Franchise Greats Dual Signature','St Kilda'],
  ['FGDS16','Luke Parker - Paul Kelly','Franchise Greats Dual Signature','Sydney Swans'],
  ['FGDS17','Dominic Sheed - Ben Cousins','Franchise Greats Dual Signature','West Coast Eagles'],
  ['FGDS18','Marcus Bontempelli - Robert Murphy','Franchise Greats Dual Signature','Western Bulldogs'],
  ['SP1','Jordan Dawson','Superstar Patch','Adelaide Crows'],
  ['SP2','Taylor Walker','Superstar Patch','Adelaide Crows'],
  ['SP3','Lachie Neale','Superstar Patch','Brisbane Lions'],
  ['SP4','Josh Dunkley','Superstar Patch','Brisbane Lions'],
  ['SP5','Samuel Walsh','Superstar Patch','Carlton'],
  ['SP6','Charlie Curnow','Superstar Patch','Carlton'],
  ['SP7','Nick Daicos','Superstar Patch','Collingwood'],
  ['SP8','Brayden Maynard','Superstar Patch','Collingwood'],
  ['SP9','Zach Merrett','Superstar Patch','Essendon'],
  ['SP10','Jake Stringer','Superstar Patch','Essendon'],
  ['SP11','Andrew Brayshaw','Superstar Patch','Fremantle'],
  ['SP12','Caleb Serong','Superstar Patch','Fremantle'],
  ['SP13','Jeremy Cameron','Superstar Patch','Geelong Cats'],
  ['SP14','Mark Blicavs','Superstar Patch','Geelong Cats'],
  ['SP15','Lachie Whitfield','Superstar Patch','GWS GIANTS'],
  ['SP16','Tom Green','Superstar Patch','GWS GIANTS'],
  ['SP17','Matt Rowell','Superstar Patch','Gold Coast SUNS'],
  ['SP18','Noah Anderson','Superstar Patch','Gold Coast SUNS'],
  ['SP19','Will Day','Superstar Patch','Hawthorn'],
  ['SP20','James Worpel','Superstar Patch','Hawthorn'],
  ['SP21','Christian Petracca','Superstar Patch','Melbourne'],
  ['SP22','Kysaiah Pickett','Superstar Patch','Melbourne'],
  ['SP23','Luke Davies-Uniacke','Superstar Patch','North Melbourne'],
  ['SP24','Jy Simpkin','Superstar Patch','North Melbourne'],
  ['SP25','Connor Rozee','Superstar Patch','Port Adelaide'],
  ['SP26','Sam Powell-Pepper','Superstar Patch','Port Adelaide'],
  ['SP27','Dion Prestia','Superstar Patch','Richmond'],
  ['SP28','Toby Nankervis','Superstar Patch','Richmond'],
  ['SP29','Jack Steele','Superstar Patch','St Kilda'],
  ['SP30','Rowan Marshall','Superstar Patch','St Kilda'],
  ['SP31','Luke Parker','Superstar Patch','Sydney Swans'],
  ['SP32','Chad Warner','Superstar Patch','Sydney Swans'],
  ['SP33','Dominic Sheed','Superstar Patch','West Coast Eagles'],
  ['SP34','Reuben Ginbey','Superstar Patch','West Coast Eagles'],
  ['SP35','Bailey Smith','Superstar Patch','Western Bulldogs'],
  ['SP36','Tom Liberatore','Superstar Patch','Western Bulldogs'],
  ['TP1','Jordan Dawson - Rory Sloane - Riley Thilthorpe','Triple Superstar Patch','Adelaide Crows'],
  ['TP2','Charlie Cameron - Hugh McCluggage - Lachie Neale','Triple Superstar Patch','Brisbane Lions'],
  ['TP3','Patrick Cripps - Sam Docherty - Samuel Walsh','Triple Superstar Patch','Carlton'],
  ['TP4','Nick Daicos - Jamie (C) Elliott - Scott Pendlebury','Triple Superstar Patch','Collingwood'],
  ['TP5','Dyson Heppell - Zach Merrett - Darcy Parish','Triple Superstar Patch','Essendon'],
  ['TP6','Andrew Brayshaw - Nathan Fyfe - Michael Walters','Triple Superstar Patch','Fremantle'],
  ['TP7','Jeremy Cameron - Patrick Dangerfield - Tom Hawkins','Triple Superstar Patch','Geelong Cats'],
  ['TP8','Stephen Coniglio - Callan Ward - Lachie Whitfield','Triple Superstar Patch','GWS GIANTS'],
  ['TP9','Ben King - Touk Miller - Matt Rowell','Triple Superstar Patch','Gold Coast SUNS'],
  ['TP10','Luke Breust - Will Day - James Sicily','Triple Superstar Patch','Hawthorn'],
  ['TP11','Clayton Oliver - Christian Petracca - Jack Viney','Triple Superstar Patch','Melbourne'],
  ['TP12','Luke Davies-Uniacke - Nick Larkey - Harry Sheezel','Triple Superstar Patch','North Melbourne'],
  ['TP13','Travis Boak - Zak Butters - Connor Rozee','Triple Superstar Patch','Port Adelaide'],
  ['TP14','Shai Bolton - Dion Prestia - Tim Taranto','Triple Superstar Patch','Richmond'],
  ['TP15','Mitch Owens - Jack Sinclair - Jack Steele','Triple Superstar Patch','St Kilda'],
  ['TP16','Isaac Heeney - Luke Parker - Tom Papley','Triple Superstar Patch','Sydney Swans'],
  ['TP17','Oscar Allen - Jack Darling - Dominic Sheed','Triple Superstar Patch','West Coast Eagles'],
  ['TP18','Marcus Bontempelli - Bailey Smith - Jackson Macrae','Triple Superstar Patch','Western Bulldogs'],
  ['SPS1','Jordan Dawson','Superstar Patch Signature Booklet','Adelaide Crows'],
  ['SPS2','Lachie Neale','Superstar Patch Signature Booklet','Brisbane Lions'],
  ['SPS3','Samuel Walsh','Superstar Patch Signature Booklet','Carlton'],
  ['SPS4','Nick Daicos','Superstar Patch Signature Booklet','Collingwood'],
  ['SPS5','Zach Merrett','Superstar Patch Signature Booklet','Essendon'],
  ['SPS6','Andrew Brayshaw','Superstar Patch Signature Booklet','Fremantle'],
  ['SPS7','Jeremy Cameron','Superstar Patch Signature Booklet','Geelong Cats'],
  ['SPS8','Lachie Whitfield','Superstar Patch Signature Booklet','GWS GIANTS'],
  ['SPS9','Matt Rowell','Superstar Patch Signature Booklet','Gold Coast SUNS'],
  ['SPS10','Will Day','Superstar Patch Signature Booklet','Hawthorn'],
  ['SPS11','Christian Petracca','Superstar Patch Signature Booklet','Melbourne'],
  ['SPS12','Luke Davies-Uniacke','Superstar Patch Signature Booklet','North Melbourne'],
  ['SPS13','Connor Rozee','Superstar Patch Signature Booklet','Port Adelaide'],
  ['SPS14','Dion Prestia','Superstar Patch Signature Booklet','Richmond'],
  ['SPS15','Jack Steele','Superstar Patch Signature Booklet','St Kilda'],
  ['SPS16','Luke Parker','Superstar Patch Signature Booklet','Sydney Swans'],
  ['SPS17','Dominic Sheed','Superstar Patch Signature Booklet','West Coast Eagles'],
  ['SPS18','Bailey Smith','Superstar Patch Signature Booklet','Western Bulldogs'],
  ['CG-BHy','Brent Harvey','Career Games','North Melbourne'],
  ['CG-MT','Michael Tuck','Career Games','Hawthorn'],
  ['CG-SBe','Shaun Burgoyne','Career Games','Hawthorn'],
  ['CG-DF','Dustin Fletcher','Career Games','Essendon'],
  ['CG-RH','Robert Harvey','Career Games','St Kilda'],
  ['CG-SMn','Simon Madden','Career Games','Essendon'],
  ['CG-DMy','David Mundy','Career Games','Fremantle'],
  ['CG-CB','Craig Bradley','Career Games','Carlton'],
  ['CG-BQ','Bernie Quinlan','Career Games','Fitzroy'],
  ['CG-BJ','Brad Johnson','Career Games','Western Bulldogs'],
  ['CG-JBy','John Blakey','Career Games','North Melbourne'],
  ['CG-GAj','Gary (jnr) Ablett','Career Games','Geelong Cats'],
  ['CG-BD','Bruce Doull','Career Games','Carlton'],
  ['CG-PRs','Paul Roos','Career Games','Fitzroy'],
  ['CG-JS','Joel Selwood','Career Games','Geelong Cats'],
  ['CG-LF','Lance Franklin','Career Games','Sydney Swans'],
  ['CG-MP','Matthew Pavlich','Career Games','Fremantle'],
  ['CG-DH','Doug Hawkins','Career Games','Footscray'],
  ['CG-JRt','Jack Riewoldt','Career Games','Richmond'],
  ['CG-LHe','Luke Hodge','Career Games','Hawthorn'],
  ['CG-KS','Kade Simpson','Career Games','Carlton'],
  ['CG-JRl','John Rantall','Career Games','Sth. Melbourne'],
  ['CG-NR','Nick Riewoldt','Career Games','St Kilda'],
  ['CG-BG','Brendon Goddard','Career Games','St Kilda'],
  ['CG-DCe','David Cloke','Career Games','Richmond'],
  ['CG-KMy','Kevin Murray','Career Games','Fitzroy'],
  ['CG-SH','Shannon Hurn','Career Games','West Coast Eagles'],
  ['CG-CE','Corey Enright','Career Games','Geelong Cats'],
  ['CG-DP','Drew Petrie','Career Games','North Melbourne'],
  ['CG-JMn','Justin Madden','Career Games','Carlton'],
  ['CG-LMs','Leigh Matthews','Career Games','Hawthorn'],
  ['CG-GD','Gary Dempsey','Career Games','Footscray'],
  ['CG-SMl','Sam Mitchell','Career Games','Hawthorn'],
  ['CG-BR','Barry Round','Career Games','Sth. Melbourne'],
  ['CG-JN','John Nicholls','Career Games','Carlton'],
  ['CG-HS','Heath Shaw','Career Games','Collingwood'],
  ['CG-IN','Ian Nankervis','Career Games','Geelong Cats'],
  ['CG-JMh','Jarrad McVeigh','Career Games','Sydney Swans'],
  ['CG-JA','Jason Akermanis','Career Games','Brisbane Lions'],
  ['CG-JBn','Jude Bolton','Career Games','Sydney Swans'],
  ['CG-PS','Paul Salmon','Career Games','Essendon'],
  ['CG-SW','Scott West','Career Games','Western Bulldogs'],
  ['CG-NB','Nathan Burke','Career Games','St Kilda'],
  ['CG-ND','Nick DalSanto','Career Games','St Kilda'],
  ['CG-SBk','Simon Black','Career Games','Brisbane Lions'],
  ['CG-SL','Stewart Loewe','Career Games','St Kilda'],
  ['CG-TWs','Ted (snr) Whitten','Career Games','Footscray'],
  ['CG-TE','Tyson Edwards','Career Games','Adelaide Crows'],
  ['CG-DR','Dick Reynolds','Career Games','Essendon'],
  ['CG-JL','Jordan Lewis','Career Games','Hawthorn'],
  ['CG-MA','Marcus Ashcroft','Career Games','Brisbane Lions'],
  ['CG-JaK','James Kelly','Career Games','Geelong Cats'],
  ['CG-RMt','Roger Merrett','Career Games','Brisbane Lions'],
  ['CG-TD','Terry Daniher','Career Games','Essendon'],
  ['CG-TS','Tony Shaw','Career Games','Collingwood'],
  ['CG-MR','Mark Ricciuto','Career Games','Adelaide Crows'],
  ['CG-RMy','Robert Murphy','Career Games','Western Bulldogs'],
  ['CG-BHt','Ben Hart','Career Games','Adelaide Crows'],
  ['CG-GAr','Glen Archer','Career Games','North Melbourne'],
  ['CG-JD','Jack Dyer','Career Games','Richmond'],
  ['CG-ST','Scott Thompson','Career Games','Adelaide Crows'],
  ['CG-TW','Tim Watson','Career Games','Essendon'],
  ['CG-AS','Adam Simpson','Career Games','North Melbourne'],
  ['CG-AL','Alistair Lynch','Career Games','Brisbane Lions'],
  ['CG-DN','David Neitz','Career Games','Melbourne'],
  ['CG-GC','Gordon Coventry','Career Games','Collingwood'],
  ['CG-PW','Paul Williams','Career Games','Sydney Swans'],
  ['CG-TC','Trent Cotchin','Career Games','Richmond'],
  ['CG-WS','Wayne Schimmelbusch','Career Games','North Melbourne'],
  ['CG-JBl','James Bartel','Career Games','Geelong Cats'],
  ['CG-SC','Shane Crawford','Career Games','Hawthorn'],
  ['CG-RG','Russell Greene','Career Games','Hawthorn'],
  ['CG-CL','Chris Langford','Career Games','Hawthorn'],
  ['CG-MO','Michael O\'Loughlin','Career Games','Sydney Swans'],
  ['CG-SE','Shane Edwards','Career Games','Richmond'],
  ['CG-DS','Don (HW) Scott','Career Games','Hawthorn'],
  ['CG-LP','Luke Power','Career Games','Brisbane Lions'],
  ['CG-NJ','Nathan Jones','Career Games','Melbourne'],
  ['CG-LT','Len Thompson','Career Games','Collingwood'],
  ['CG-SG','Shannon Grant','Career Games','North Melbourne'],
  ['CG-BB','Barry Breen','Career Games','St Kilda'],
  ['CG-FB','Francis Bourke','Career Games','Richmond'],
  ['CG-GF','Garry Foulds','Career Games','Essendon'],
  ['CG-GW','Gavin Wanganeen','Career Games','Port Adelaide'],
  ['CG-KC','Kane Cornes','Career Games','Port Adelaide'],
  ['CG-KMe','Kelvin Moore','Career Games','Hawthorn'],
  ['CG-MMy','Marc Murphy','Career Games','Carlton'],
  ['CG-MMn','Michael Martyn','Career Games','North Melbourne'],
  ['CG-RS','Rohan Smith','Career Games','Western Bulldogs'],
  ['CG-SN','John Newman','Career Games','Geelong Cats'],
  ['CG-LHs','Lenny Hayes','Career Games','St Kilda'],
  ['CG-WC','Wayne Campbell','Career Games','Richmond'],
  ['CG-JT','Jack Titus','Career Games','Richmond'],
  ['CG-KG','Keith Greig','Career Games','North Melbourne'],
  ['CG-JoK','Josh Kennedy','Career Games','Sydney Swans'],
  ['CG-RC','Rod Carter','Career Games','Sydney Swans'],
  ['CG-SJ','Steve Johnson','Career Games','Geelong Cats'],
  ['CG-AS','Anthony Stevens','Career Games','North Melbourne'],
  ['CG-DMn','Darren Milburn','Career Games','Geelong Cats'],
  ['CG-MB','Matthew Boyd','Career Games','Western Bulldogs'],
  ['CGS-BHy','Brent Harvey','Career Games Signature','North Melbourne'],
  ['CGS-MT','Michael Tuck','Career Games Signature','Hawthorn'],
  ['CGS-SBe','Shaun Burgoyne','Career Games Signature','Hawthorn'],
  ['CGS-DF','Dustin Fletcher','Career Games Signature','Essendon'],
  ['CGS-RH','Robert Harvey','Career Games Signature','St Kilda'],
  ['CGS-SMn','Simon Madden','Career Games Signature','Essendon'],
  ['CGS-DMy','David Mundy','Career Games Signature','Fremantle'],
  ['CGS-CB','Craig Bradley','Career Games Signature','Carlton'],
  ['CGS-BQ','Bernie Quinlan','Career Games Signature','Fitzroy'],
  ['CGS-BJ','Brad Johnson','Career Games Signature','Western Bulldogs'],
  ['CGS-JBy','John Blakey','Career Games Signature','North Melbourne'],
  ['CGS-GAj','Gary (jnr) Ablett','Career Games Signature','Geelong Cats'],
  ['CGS-BD','Bruce Doull','Career Games Signature','Carlton'],
  ['CGS-PRs','Paul Roos','Career Games Signature','Sydney Swans'],
  ['CGS-JS','Joel Selwood','Career Games Signature','Geelong Cats'],
  ['CGS-LF','Lance Franklin','Career Games Signature','Sydney Swans'],
  ['CGS-MP','Matthew Pavlich','Career Games Signature','Fremantle'],
  ['CGS-DH','Doug Hawkins','Career Games Signature','Footscray'],
  ['CGS-JRt','Jack Riewoldt','Career Games Signature','Richmond'],
  ['CGS-LHe','Luke Hodge','Career Games Signature','Hawthorn'],
  ['CGS-KS','Kade Simpson','Career Games Signature','Carlton'],
  ['CGS-JRl','John Rantall','Career Games Signature','Sth. Melbourne'],
  ['CGS-NR','Nick Riewoldt','Career Games Signature','St Kilda'],
  ['CGS-BG','Brendon Goddard','Career Games Signature','St Kilda'],
  ['CGS-DCe','David Cloke','Career Games Signature','Richmond'],
  ['CGS-SH','Shannon Hurn','Career Games Signature','West Coast Eagles'],
  ['PG-61','Darren Jarman','Premiership Glory','Adelaide Crows'],
  ['PG-62','Kane Johnson','Premiership Glory','Adelaide Crows'],
  ['PG-63','Jonathon Brown','Premiership Glory','Brisbane Lions'],
  ['PG-64','Craig McRae','Premiership Glory','Brisbane Lions'],
  ['PG-65','Craig Bradley','Premiership Glory','Carlton'],
  ['PG-66','Robert Walls','Premiership Glory','Carlton'],
  ['PG-67','Luke Ball','Premiership Glory','Collingwood'],
  ['PG-68','Steele Sidebottom','Premiership Glory','Collingwood'],
  ['PG-69','Scott Lucas','Premiership Glory','Essendon'],
  ['PG-70','Dean Wallis','Premiership Glory','Essendon'],
  ['PG-71','Steve Johnson','Premiership Glory','Geelong Cats'],
  ['PG-72','Brad Ottens','Premiership Glory','Geelong Cats'],
  ['PG-73','Jordan Lewis','Premiership Glory','Hawthorn'],
  ['PG-74','Ray Wilson','Premiership Glory','Hawthorn'],
  ['PG-75','Max Gawn','Premiership Glory','Melbourne'],
  ['PG-76','Christian Petracca','Premiership Glory','Melbourne'],
  ['PG-77','Glen Archer','Premiership Glory','North Melbourne'],
  ['PG-78','Corey McKernan','Premiership Glory','North Melbourne'],
  ['PG-79','Kane Cornes','Premiership Glory','Port Adelaide'],
  ['PG-80','Stuart Dew','Premiership Glory','Port Adelaide'],
  ['PG-81','Shane Edwards','Premiership Glory','Richmond'],
  ['PG-82','Kane Lambert','Premiership Glory','Richmond'],
  ['PG-83','Barry Breen','Premiership Glory','St Kilda'],
  ['PG-84','Ross (SK) Smith','Premiership Glory','St Kilda'],
  ['PG-85','Leo Barry','Premiership Glory','Sydney Swans'],
  ['PG-86','Jarrad McVeigh','Premiership Glory','Sydney Swans'],
  ['PG-87','Ben Cousins','Premiership Glory','West Coast Eagles'],
  ['PG-88','Dean Cox','Premiership Glory','West Coast Eagles'],
  ['PG-89','Marcus Bontempelli','Premiership Glory','Western Bulldogs'],
  ['PG-90','Thomas Boyd','Premiership Glory','Western Bulldogs'],
  ['PGS-61','Darren Jarman','Premiership Glory Signature','Adelaide Crows'],
  ['PGS-62','Kane Johnson','Premiership Glory Signature','Adelaide Crows'],
  ['PGS-62','Kane Johnson','Premiership Glory Redemption','Adelaide Crows'],
  ['PGS-63','Jonathon Brown','Premiership Glory Signature','Brisbane Lions'],
  ['PGS-64','Craig McRae','Premiership Glory Signature','Brisbane Lions'],
  ['PGS-65','Craig Bradley','Premiership Glory Signature','Carlton'],
  ['PGS-66','Robert Walls','Premiership Glory Signature','Carlton'],
  ['PGS-67','Luke Ball','Premiership Glory Signature','Collingwood'],
  ['PGS-68','Steele Sidebottom','Premiership Glory Signature','Collingwood'],
  ['PGS-69','Scott Lucas','Premiership Glory Signature','Essendon'],
  ['PGS-70','Dean Wallis','Premiership Glory Signature','Essendon'],
  ['PGS-71','Steve Johnson','Premiership Glory Signature','Geelong Cats'],
  ['PGS-72','Brad Ottens','Premiership Glory Signature','Geelong Cats'],
  ['PGS-73','Jordan Lewis','Premiership Glory Signature','Hawthorn'],
  ['PGS-74','Ray Wilson','Premiership Glory Signature','Hawthorn'],
  ['PGS-75','Max Gawn','Premiership Glory Signature','Melbourne'],
  ['PGS-76','Christian Petracca','Premiership Glory Signature','Melbourne'],
  ['PGS-77','Glen Archer','Premiership Glory Signature','North Melbourne'],
  ['PGS-78','Corey McKernan','Premiership Glory Signature','North Melbourne'],
  ['PGS-79','Kane Cornes','Premiership Glory Signature','Port Adelaide'],
  ['PGS-80','Stuart Dew','Premiership Glory Signature','Port Adelaide'],
  ['PGS-81','Shane Edwards','Premiership Glory Signature','Richmond'],
  ['PGS-82','Kane Lambert','Premiership Glory Signature','Richmond'],
  ['PGS-83','Barry Breen','Premiership Glory Signature','St Kilda'],
  ['PGS-84','Ross (SK) Smith','Premiership Glory Signature','St Kilda'],
  ['PGS-85','Leo Barry','Premiership Glory Signature','Sydney Swans'],
  ['PGS-86','Jarrad McVeigh','Premiership Glory Signature','Sydney Swans'],
  ['PGS-87','Ben Cousins','Premiership Glory Signature','West Coast Eagles'],
  ['PGS-88','Dean Cox','Premiership Glory Signature','West Coast Eagles'],
  ['PGS-89','Marcus Bontempelli','Premiership Glory Signature','Western Bulldogs'],
  ['PGS-90','Thomas Boyd','Premiership Glory Signature','Western Bulldogs'],
  ['GG-LF','Lance Franklin','Goalkicking Greats','Sydney Swans'],
  ['GG-JR','Jack Riewoldt','Goalkicking Greats','Richmond'],
  ['GGS-DB','Daniel Bradshaw','Goalkicking Greats Signature','Brisbane Lions'],
  ['GGS-AL','Alistair Lynch','Goalkicking Greats Signature','Brisbane Lions'],
  ['GGS-SMa','Simon Madden','Goalkicking Greats Signature','Essendon'],
  ['GGS-PSa','Paul Salmon','Goalkicking Greats Signature','Essendon'],
  ['GGS-RO','Richard Osborne','Goalkicking Greats Signature','Fitzroy'],
  ['GGS-KT','Kelvin Templeton','Goalkicking Greats Signature','Footscray'],
  ['GGS-SJ','Steve Johnson','Goalkicking Greats Signature','Geelong Cats'],
  ['GGS-LM','Leigh Matthews','Goalkicking Greats Signature','Hawthorn'],
  ['GGS-MM','Michael Moncrieff','Goalkicking Greats Signature','Hawthorn'],
  ['GGS-JR','Jarryd Roughead','Goalkicking Greats Signature','Hawthorn'],
  ['GGS-BHy','Brent Harvey','Goalkicking Greats Signature','North Melbourne'],
  ['GGS-JL','John Longmire','Goalkicking Greats Signature','North Melbourne'],
  ['GGS-FG','Fraser Gehrig','Goalkicking Greats Signature','St Kilda'],
  ['GGS-SMi','Stephen Milne','Goalkicking Greats Signature','St Kilda'],
  ['GGS-NR','Nick Riewoldt','Goalkicking Greats Signature','St Kilda'],
  ['GGS-BHl','Barry Hall','Goalkicking Greats Signature','Sydney Swans'],
  ['GGS-LF','Lance Franklin','Goalkicking Greats Signature','Sydney Swans'],
  ['GGS-JR','Jack Riewoldt','Goalkicking Greats Signature','Richmond'],
  ['C1','Jordan Dawson','Club Captains','Adelaide Crows'],
  ['C2','Taylor Walker','Club Captains','Adelaide Crows'],
  ['C3','Mark Ricciuto','Club Captains','Adelaide Crows'],
  ['C4','Chris McDermott','Club Captains','Adelaide Crows'],
  ['C5','Harris Andrews','Club Captains','Brisbane Lions'],
  ['C6','Jonathon Brown','Club Captains','Brisbane Lions'],
  ['C7','Michael Voss','Club Captains','Brisbane Lions'],
  ['C8','Alistair Lynch','Club Captains','Brisbane Lions'],
  ['C9','Patrick Cripps','Club Captains','Carlton'],
  ['C10','Stephen Kernahan','Club Captains','Carlton'],
  ['C11','Mike Fitzpatrick','Club Captains','Carlton'],
  ['C12','Ron Barassi','Club Captains','Carlton'],
  ['C13','Darcy Moore','Club Captains','Collingwood'],
  ['C14','Scott Pendlebury','Club Captains','Collingwood'],
  ['C15','Tony Shaw','Club Captains','Collingwood'],
  ['C16','Des Tuddenham','Club Captains','Collingwood'],
  ['C17','Zach Merrett','Club Captains','Essendon'],
  ['C18','Dyson Heppell','Club Captains','Essendon'],
  ['C19','James Hird','Club Captains','Essendon'],
  ['C20','Terry Daniher','Club Captains','Essendon'],
  ['C21','Alex Pearce','Club Captains','Fremantle'],
  ['C22','Nathan Fyfe','Club Captains','Fremantle'],
  ['C23','Matthew Pavlich','Club Captains','Fremantle'],
  ['C24','Ben Allan','Club Captains','Fremantle'],
  ['C25','Patrick Dangerfield','Club Captains','Geelong Cats'],
  ['C26','Joel Selwood','Club Captains','Geelong Cats'],
  ['C27','Barry Stoneham','Club Captains','Geelong Cats'],
  ['C28','Gary Ablett','Club Captains','Geelong Cats'],
  ['C29','Toby Greene','Club Captains','GWS GIANTS'],
  ['C30','Callan Ward','Club Captains','GWS GIANTS'],
  ['C31','Stephen Coniglio','Club Captains','GWS GIANTS'],
  ['C32','Phil Davis','Club Captains','GWS GIANTS'],
  ['C33','Touk Miller','Club Captains','Gold Coast SUNS'],
  ['C34','David Swallow','Club Captains','Gold Coast SUNS'],
  ['C35','Tom.J Lynch','Club Captains','Gold Coast SUNS'],
  ['C36','Gary (jnr) Ablett','Club Captains','Gold Coast SUNS'],
  ['C37','James Sicily','Club Captains','Hawthorn'],
  ['C38','Luke Hodge','Club Captains','Hawthorn'],
  ['C39','Leigh Matthews','Club Captains','Hawthorn'],
  ['C40','David Parkin','Club Captains','Hawthorn'],
  ['C41','Max Gawn','Club Captains','Melbourne'],
  ['C42','Todd Viney','Club Captains','Melbourne'],
  ['C43','Robert Flower','Club Captains','Melbourne'],
  ['C44','Ron Barassi','Club Captains','Melbourne'],
  ['C45','Jy Simpkin','Club Captains','North Melbourne'],
  ['C46','Jack Ziebell','Club Captains','North Melbourne'],
  ['C47','Wayne Carey','Club Captains','North Melbourne'],
  ['C48','Wayne Schimmelbusch','Club Captains','North Melbourne'],
  ['C49','Connor Rozee','Club Captains','Port Adelaide'],
  ['C50','Travis Boak','Club Captains','Port Adelaide'],
  ['C51','Domenic Cassisi','Club Captains','Port Adelaide'],
  ['C52','Gavin Wanganeen','Club Captains','Port Adelaide'],
  ['C53','Toby Nankervis','Club Captains','Richmond'],
  ['C54','Trent Cotchin','Club Captains','Richmond'],
  ['C55','Bruce Monteath','Club Captains','Richmond'],
  ['C56','Royce Hart','Club Captains','Richmond'],
  ['C57','Jack Steele','Club Captains','St Kilda'],
  ['C58','Nick Riewoldt','Club Captains','St Kilda'],
  ['C59','Lenny Hayes','Club Captains','St Kilda'],
  ['C60','Trevor Barker','Club Captains','St Kilda'],
  ['C61','Callum Mills','Club Captains','Sydney Swans'],
  ['C62','Barry Hall','Club Captains','Sydney Swans'],
  ['C63','Paul Kelly','Club Captains','Sydney Swans'],
  ['C64','Bob Skilton','Club Captains','Sth. Melbourne'],
  ['C65','Oscar Allen','Club Captains','West Coast Eagles'],
  ['C66','Shannon Hurn','Club Captains','West Coast Eagles'],
  ['C67','Ben Cousins','Club Captains','West Coast Eagles'],
  ['C68','John Worsfold','Club Captains','West Coast Eagles'],
  ['C69','Marcus Bontempelli','Club Captains','Western Bulldogs'],
  ['C70','Robert Murphy','Club Captains','Western Bulldogs'],
  ['C71','Charlie Sutton','Club Captains','Footscray'],
  ['C71','Charlie Sutton','Club Captains Redemption','Footscray'],
  ['C72','Ted (snr) Whitten','Club Captains','Footscray'],
  ['LSC-JS','Joel Selwood','Captain Signature','Geelong Cats'],
  ['LSC-SK','Stephen Kernahan','Captain Signature','Carlton'],
  ['LSC-NR','Nick Riewoldt','Captain Signature','St Kilda'],
  ['LSC-MW','Michael Voss','Captain Signature','Brisbane Lions'],
  ['LSC-SP','Scott Pendlebury','Captain Signature','Collingwood'],
  ['LSC-MP','Matthew Pavlich','Captain Signature','Fremantle'],
  ['LSC-TC','Trent Cotchin','Captain Signature','Richmond'],
  ['LSC-JN','John Nicholls','Captain Signature','Carlton'],
  ['LSC-WC','Wayne Carey','Captain Signature','North Melbourne'],
  ['E1','Kevin Sheedy','Evolution','Richmond'],
  ['E2','Michael Malthouse','Evolution','Richmond'],
  ['E3','Jock McHale','Evolution','Collingwood'],
  ['E4','Leigh Matthews','Evolution','Hawthorn'],
  ['E5','David Parkin','Evolution','Hawthorn'],
  ['E6','Ron Barassi','Evolution','Melbourne'],
  ['E7','Norm Smith','Evolution','Melbourne'],
  ['E8','Allan Jeans','Evolution','St Kilda'],
  ['E9','Rodney Eade','Evolution','Hawthorn'],
  ['E10','Paul Roos','Evolution','Fitzroy'],
  ['E11','Robert Walls','Evolution','Carlton'],
  ['E12','John Worsfold','Evolution','West Coast Eagles'],
  ['E13','Tom Hafey','Evolution','Richmond'],
  ['E14','John (snr) Kennedy','Evolution','Hawthorn'],
  ['E15','Percy Bentley','Evolution','Richmond'],
  ['E16','Dick Reynolds','Evolution','Essendon'],
  ['E17','Phonse Kyne','Evolution','Collingwood'],
  ['E18','Terry Wallace','Evolution','Hawthorn'],
  ['E19','Nathan Buckley','Evolution','Collingwood'],
  ['E20','Gary Ayres','Evolution','Hawthorn'],
  ['E21','Denis Pagan','Evolution','North Melbourne'],
  ['E22','Mark Thompson','Evolution','Essendon'],
  ['E23','Mark Williams','Evolution','Collingwood'],
  ['E24','Frank (Checker) Hughes','Evolution','Richmond'],
  ['E25','Reg Hickey','Evolution','Geelong Cats'],
  ['E26','Brett Ratten','Evolution','Carlton'],
  ['E27','Leon Cameron','Evolution','Western Bulldogs'],
  ['E28','Dan Minogue','Evolution','Collingwood'],
  ['E29','Bob Rose','Evolution','Collingwood'],
  ['E30','John Northey','Evolution','Richmond'],
  ['ES-KS','Kevin Sheedy','Evolution Signature','Richmond'],
  ['ES-MM','Michael Malthouse','Evolution Signature','Richmond'],
  ['ES-LM','Leigh Matthews','Evolution Signature','Hawthorn'],
  ['ES-DPk','David Parkin','Evolution Signature','Hawthorn'],
  ['ES-RE','Rodney Eade','Evolution Signature','Hawthorn'],
  ['ES-PR','Paul Roos','Evolution Signature','Fitzroy'],
  ['ES-RW','Robert Walls','Evolution Signature','Carlton'],
  ['EES-JW','John Worsfold','Evolution Signature','West Coast Eagles'],
  ['ES-TW','Terry Wallace','Evolution Signature','Hawthorn'],
  ['ES-NB','Nathan Buckley','Evolution Signature','Collingwood'],
  ['ES-GA','Gary Ayres','Evolution Signature','Hawthorn'],
  ['ES-DPg','Denis Pagan','Evolution Signature','North Melbourne'],
  ['ES-MT','Mark Thompson','Evolution Signature','Essendon'],
  ['ES-MW','Mark Williams','Evolution Signature','Collingwood'],
  ['ES-BR','Brett Ratten','Evolution Signature','Carlton'],
  ['ES-LC','Leon Cameron','Evolution Signature','Western Bulldogs'],
  ['ES-JN','John Northey','Evolution Signature','Richmond'],
  ['PPCS-DP','David Parkin','Prem Player Coach Signature','Hawthorn'],
  ['PPCS-KS','Kevin Sheedy','Prem Player Coach Signature','Richmond'],
  ['PPCS-RW','Robert Walls','Prem Player Coach Signature','Carlton'],
  ['PPCS-LM','Leigh Matthews','Prem Player Coach Signature','Hawthorn'],
  ['PPCS-MM','Michael Malthouse','Prem Player Coach Signature','Richmond'],
  ['PPCS-MB','Malcolm Blight','Prem Player Coach Signature','North Melbourne'],
  ['PPCS-JW','John Worsfold','Prem Player Coach Signature','West Coast Eagles'],
  ['PPCS-MT','Mark Thompson','Prem Player Coach Signature','Essendon'],
  ['PPCS-CS','Chris Scott','Prem Player Coach Signature','Brisbane Lions'],
  ['PPCS-DH','Damien Hardwick','Prem Player Coach Signature','Port Adelaide'],
  ['PPCS-AS','Adam Simpson','Prem Player Coach Signature','North Melbourne'],
  ['PPCS-SG','Simon Goodwin','Prem Player Coach Signature','Adelaide Crows'],
  ['PPCS-JN','John Nicholls','Prem Player Coach Signature','Carlton'],
  ['PPCS-AJ','Alex Jesaulenko','Prem Player Coach Signature','Carlton'],
  ['PPCS-JL','John Longmire','Prem Player Coach Signature','North Melbourne'],
  ['PPCS-CM','Craig McRae','Prem Player Coach Signature','Brisbane Lions'],
  ['PBDS1','Simon Black','Premiership Brownlow Double Signature','Brisbane Lions'],
  ['PBDS2','Gavin Wanganeen','Premiership Brownlow Double Signature','Essendon'],
  ['PBDS3','Gary (jnr) Ablett','Premiership Brownlow Double Signature','Geelong Cats'],
  ['PBDS4','Sam Mitchell','Premiership Brownlow Double Signature','Hawthorn'],
  ['PBDS5','Trent Cotchin','Premiership Brownlow Double Signature','Richmond'],
  ['PBDS6','Ian Stewart','Premiership Brownlow Double Signature','St Kilda'],
  ['GKS-LF','Lance Franklin','1000 Goalkicker Signature','Sydney Swans'],
  ['GGDS1','Lance Franklin','Goalkicking Greats Dual Signature','Sydney Swans'],
  ['LSCB1','Joel Selwood','Longest Serving Captains Signature','Geelong Cats'],
];

